package com.mangala.wallet.features.addressbook.domain.sharing

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.net.Uri
import android.provider.MediaStore
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asAndroidBitmap
import androidx.core.content.FileProvider
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.koin.core.component.KoinComponent
import org.koin.core.component.inject
import java.io.File
import java.io.FileOutputStream
import java.io.IOException

actual class ImageSharingHelper : KoinComponent {
    
    private val context: Context by inject()
    
    actual suspend fun shareQrImage(
        image: ImageBitmap,
        title: String,
        text: String?
    ): ShareResult = withContext(Dispatchers.IO) {
        try {
            val bitmap = image.asAndroidBitmap()
            val imageUri = saveBitmapToCache(bitmap, "qr_${System.currentTimeMillis()}.png")
            
            if (imageUri != null) {
                val shareIntent = Intent().apply {
                    action = Intent.ACTION_SEND
                    type = "image/png"
                    putExtra(Intent.EXTRA_STREAM, imageUri)
                    putExtra(Intent.EXTRA_TITLE, title)
                    text?.let { putExtra(Intent.EXTRA_TEXT, it) }
                    addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                }
                
                val chooser = Intent.createChooser(shareIntent, "Share QR Code")
                chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                context.startActivity(chooser)
                
                ShareResult.Success
            } else {
                ShareResult.Error("Failed to save image")
            }
        } catch (e: Exception) {
            ShareResult.Error(e.message ?: "Unknown error")
        }
    }
    
    actual suspend fun saveQrImageToGallery(
        image: ImageBitmap,
        filename: String
    ): SaveResult = withContext(Dispatchers.IO) {
        try {
            val bitmap = image.asAndroidBitmap()
            val savedUri = MediaStore.Images.Media.insertImage(
                context.contentResolver,
                bitmap,
                filename,
                "QR Code generated by Mangala Wallet"
            )
            
            if (savedUri != null) {
                SaveResult.Success
            } else {
                SaveResult.Error("Failed to save to gallery")
            }
        } catch (e: SecurityException) {
            SaveResult.PermissionDenied
        } catch (e: Exception) {
            SaveResult.Error(e.message ?: "Unknown error")
        }
    }
    
    private fun saveBitmapToCache(bitmap: Bitmap, filename: String): Uri? {
        return try {
            val cachePath = File(context.cacheDir, "qr_images")
            cachePath.mkdirs()
            
            val file = File(cachePath, filename)
            val fileOutputStream = FileOutputStream(file)
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, fileOutputStream)
            fileOutputStream.close()
            
            FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )
        } catch (e: IOException) {
            null
        }
    }
}