PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE BlockchainEntity (
    uid TEXT PRIMARY KEY,
    name TEXT,
    eip3091url TEXT
);
INSERT INTO BlockchainEntity VALUES('swagbucks','SwagBucks','');
INSERT INTO BlockchainEntity VALUES('tuxcoin','Tuxcoin','');
INSERT INTO BlockchainEntity VALUES('moneta','Moneta','');
INSERT INTO BlockchainEntity VALUES('flare-networks','Flare','');
INSERT INTO BlockchainEntity VALUES('metaverse-etp','Metaverse ETP','');
INSERT INTO BlockchainEntity VALUES('nem','NEM','');
INSERT INTO BlockchainEntity VALUES('polymesh','Polymesh','');
INSERT INTO BlockchainEntity VALUES('icon','ICON','');
INSERT INTO BlockchainEntity VALUES('platincoin','PlatinCoin','');
INSERT INTO BlockchainEntity VALUES('stealthcoin','Stealth','');
INSERT INTO BlockchainEntity VALUES('stratis','Stratis','');
INSERT INTO BlockchainEntity VALUES('aptos','Aptos','');
INSERT INTO BlockchainEntity VALUES('helio','Helio','');
INSERT INTO BlockchainEntity VALUES('nuls','Nuls','');
INSERT INTO BlockchainEntity VALUES('whitebit','WhiteBIT Token','');
INSERT INTO BlockchainEntity VALUES('terra-luna-2','Terra','');
INSERT INTO BlockchainEntity VALUES('nxt','NXT','');
INSERT INTO BlockchainEntity VALUES('experience-chain','eXPerience Chain','');
INSERT INTO BlockchainEntity VALUES('ethereum-pow-iou','EthereumPoW','');
INSERT INTO BlockchainEntity VALUES('zcash','Zcash','');
INSERT INTO BlockchainEntity VALUES('hoo-smart-chain','Hoo Smart Chain','');
INSERT INTO BlockchainEntity VALUES('dero','Dero','');
INSERT INTO BlockchainEntity VALUES('qlink','QLC Chain','');
INSERT INTO BlockchainEntity VALUES('counterparty','Counterparty','');
INSERT INTO BlockchainEntity VALUES('bitcoin-gold','Bitcoin Gold','');
INSERT INTO BlockchainEntity VALUES('aok','AOK','');
INSERT INTO BlockchainEntity VALUES('insanecoin','INSaNe','');
INSERT INTO BlockchainEntity VALUES('auxilium','Auxilium','');
INSERT INTO BlockchainEntity VALUES('super-zero','Sero','');
INSERT INTO BlockchainEntity VALUES('aleph-zero','Aleph Zero','');
INSERT INTO BlockchainEntity VALUES('blockchain-of-hash-power','Blockchain of Hash Power','');
INSERT INTO BlockchainEntity VALUES('bnb-beacon-chain','BNB Beacon Chain','');
INSERT INTO BlockchainEntity VALUES('canto','CANTO','');
INSERT INTO BlockchainEntity VALUES('komodo','Komodo','');
INSERT INTO BlockchainEntity VALUES('dogechain','Dogechain','');
INSERT INTO BlockchainEntity VALUES('achain','Achain','');
INSERT INTO BlockchainEntity VALUES('vite','Vite','');
INSERT INTO BlockchainEntity VALUES('gochain','GoChain','');
INSERT INTO BlockchainEntity VALUES('telos-coin','Teloscoin','');
INSERT INTO BlockchainEntity VALUES('enq-enecuum','Enecuum','');
INSERT INTO BlockchainEntity VALUES('mdex','Mdex','');
INSERT INTO BlockchainEntity VALUES('kusama','Kusama','');
INSERT INTO BlockchainEntity VALUES('oasis','Oasis','');
INSERT INTO BlockchainEntity VALUES('kaspa','Kaspa','');
INSERT INTO BlockchainEntity VALUES('velas','Velas','');
INSERT INTO BlockchainEntity VALUES('polis-chain','Polis Chain','');
INSERT INTO BlockchainEntity VALUES('shiden network','Shiden Network','');
INSERT INTO BlockchainEntity VALUES('biblepay','BiblePay','');
INSERT INTO BlockchainEntity VALUES('unknown-fair-object','Unknown Fair Object','');
INSERT INTO BlockchainEntity VALUES('buyucoin-token','BuyUCoin Token','');
INSERT INTO BlockchainEntity VALUES('defichain','DeFiChain','');
INSERT INTO BlockchainEntity VALUES('zelcash','Flux','');
INSERT INTO BlockchainEntity VALUES('mercury','Mercury','');
INSERT INTO BlockchainEntity VALUES('step-network','step-network','');
INSERT INTO BlockchainEntity VALUES('deso','Decentralized Social','');
INSERT INTO BlockchainEntity VALUES('bontecoin','Bontecoin','');
INSERT INTO BlockchainEntity VALUES('arionum','Arionum','');
INSERT INTO BlockchainEntity VALUES('hoo','Hoo','');
INSERT INTO BlockchainEntity VALUES('bitcrex-coin','Bitcrex Coin','');
INSERT INTO BlockchainEntity VALUES('pigeoncoin','Pigeoncoin','');
INSERT INTO BlockchainEntity VALUES('kardiachain','KardiaChain','');
INSERT INTO BlockchainEntity VALUES('mixin-network','Mixin Network','');
INSERT INTO BlockchainEntity VALUES('ucoin','Ucoin','');
INSERT INTO BlockchainEntity VALUES('dinero','Dinero','');
INSERT INTO BlockchainEntity VALUES('catocoin','CatoCoin','');
INSERT INTO BlockchainEntity VALUES('vericoin','VeriCoin','');
INSERT INTO BlockchainEntity VALUES('bitflowers','bitFlowers','');
INSERT INTO BlockchainEntity VALUES('scribe','Scribe','');
INSERT INTO BlockchainEntity VALUES('bitcash','BitCash','');
INSERT INTO BlockchainEntity VALUES('sjwcoin','SJWCoin','');
INSERT INTO BlockchainEntity VALUES('bitweb','Bitweb','');
INSERT INTO BlockchainEntity VALUES('gbrick','Gbrick','');
INSERT INTO BlockchainEntity VALUES('exosama-network','Moonsama','');
INSERT INTO BlockchainEntity VALUES('filestar','FileStar','');
INSERT INTO BlockchainEntity VALUES('codex','Codex','');
INSERT INTO BlockchainEntity VALUES('exosama','exosama','');
INSERT INTO BlockchainEntity VALUES('unitus','Unitus','');
INSERT INTO BlockchainEntity VALUES('shadow-token','Shadow Token','');
INSERT INTO BlockchainEntity VALUES('thorchain','Thorchain','');
INSERT INTO BlockchainEntity VALUES('etitanium','eTitanium','');
INSERT INTO BlockchainEntity VALUES('ultra-clear','Ultra Clear','');
INSERT INTO BlockchainEntity VALUES('hirevibes','HireVibes','');
INSERT INTO BlockchainEntity VALUES('mincoin','Mincoin','');
INSERT INTO BlockchainEntity VALUES('shrooms','Shrooms','');
INSERT INTO BlockchainEntity VALUES('ioex','ioeX','');
INSERT INTO BlockchainEntity VALUES('machinecoin','Machinecoin','');
INSERT INTO BlockchainEntity VALUES('spectresecuritycoin','SpectreSecurityCoin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-adult','Bitcoin Adult','');
INSERT INTO BlockchainEntity VALUES('milkomeda-cardano','Milkomeda (Cardano)','');
INSERT INTO BlockchainEntity VALUES('acala','Acala','');
INSERT INTO BlockchainEntity VALUES('defi-kingdoms-blockchain','DFK Chain','');
INSERT INTO BlockchainEntity VALUES('conflux','Conflux','');
INSERT INTO BlockchainEntity VALUES('cube-network','Cube Network','');
INSERT INTO BlockchainEntity VALUES('bzedge','BZEdge','');
INSERT INTO BlockchainEntity VALUES('ombre','Ombre','');
INSERT INTO BlockchainEntity VALUES('titan-coin','Titan Coin','');
INSERT INTO BlockchainEntity VALUES('omega','OMEGA','');
INSERT INTO BlockchainEntity VALUES('hycon','Hycon','');
INSERT INTO BlockchainEntity VALUES('scrypta','Scrypta','');
INSERT INTO BlockchainEntity VALUES('plug-chain','Plug Chain','');
INSERT INTO BlockchainEntity VALUES('nexalt','Nexalt','');
INSERT INTO BlockchainEntity VALUES('true-chain','TrueChain','');
INSERT INTO BlockchainEntity VALUES('tekcoin','TEKcoin','');
INSERT INTO BlockchainEntity VALUES('aquariuscoin','AquariusCoin','');
INSERT INTO BlockchainEntity VALUES('axe','Axe','');
INSERT INTO BlockchainEntity VALUES('xp','XP','');
INSERT INTO BlockchainEntity VALUES('tenup','Tenup','');
INSERT INTO BlockchainEntity VALUES('cash2','Cash2','');
INSERT INTO BlockchainEntity VALUES('proxynode','ProxyNode','');
INSERT INTO BlockchainEntity VALUES('uraniumx','UraniumX','');
INSERT INTO BlockchainEntity VALUES('arion','Arion','');
INSERT INTO BlockchainEntity VALUES('decentrahub-coin','Decentrahub Coin','');
INSERT INTO BlockchainEntity VALUES('veco','Veco','');
INSERT INTO BlockchainEntity VALUES('incakoin','IncaKoin','');
INSERT INTO BlockchainEntity VALUES('zent-cash','Zent Cash','');
INSERT INTO BlockchainEntity VALUES('sucrecoin','Sucrecoin','');
INSERT INTO BlockchainEntity VALUES('buysell','BuySell','');
INSERT INTO BlockchainEntity VALUES('southxchange-coin','SouthXchange Coin','');
INSERT INTO BlockchainEntity VALUES('antra','Antra','');
INSERT INTO BlockchainEntity VALUES('grin','Grin','');
INSERT INTO BlockchainEntity VALUES('nodestats','Nodestats','');
INSERT INTO BlockchainEntity VALUES('monerov','MoneroV','');
INSERT INTO BlockchainEntity VALUES('ilcoin','ILCOIN','');
INSERT INTO BlockchainEntity VALUES('millenniumclub','MillenniumClub Coin','');
INSERT INTO BlockchainEntity VALUES('novacoin','Novacoin','');
INSERT INTO BlockchainEntity VALUES('2x2','2X2','');
INSERT INTO BlockchainEntity VALUES('rocket-fund','Rocket Fund','');
INSERT INTO BlockchainEntity VALUES('heptafranc','HEPTAFRANC','');
INSERT INTO BlockchainEntity VALUES('safcoin','SafCoin','');
INSERT INTO BlockchainEntity VALUES('universal-currency','Universal Currency','');
INSERT INTO BlockchainEntity VALUES('ahatoken','AhaToken','');
INSERT INTO BlockchainEntity VALUES('bigbang-core','BigBang Core','');
INSERT INTO BlockchainEntity VALUES('europecoin','EuropeCoin','');
INSERT INTO BlockchainEntity VALUES('hebeblock','Hebeblock','');
INSERT INTO BlockchainEntity VALUES('credit','TerraCredit','');
INSERT INTO BlockchainEntity VALUES('kmushicoin','Kmushicoin','');
INSERT INTO BlockchainEntity VALUES('digital-money-bits','Digital Money Bits','');
INSERT INTO BlockchainEntity VALUES('masterwin','MasterWin','');
INSERT INTO BlockchainEntity VALUES('ripple-alpha','Ripple Alpha','');
INSERT INTO BlockchainEntity VALUES('gictrade','GICTrade','');
INSERT INTO BlockchainEntity VALUES('bficoin','Bficoin','');
INSERT INTO BlockchainEntity VALUES('index-chain','Index Chain','');
INSERT INTO BlockchainEntity VALUES('konjungate','KONJUNGATE','');
INSERT INTO BlockchainEntity VALUES('glass-chain','Glass Chain','');
INSERT INTO BlockchainEntity VALUES('thegcccoin','Global Cryptocurrency','');
INSERT INTO BlockchainEntity VALUES('hodlcoin','HOdlcoin','');
INSERT INTO BlockchainEntity VALUES('digitalcoin','Digitalcoin','');
INSERT INTO BlockchainEntity VALUES('eureka-coin','Eureka Coin','');
INSERT INTO BlockchainEntity VALUES('oasis-network','Oasis Network','');
INSERT INTO BlockchainEntity VALUES('the-forbidden-forest','The Forbidden Forest','');
INSERT INTO BlockchainEntity VALUES('adamant-messenger','ADAMANT Messenger','');
INSERT INTO BlockchainEntity VALUES('nyzo','Nyzo','');
INSERT INTO BlockchainEntity VALUES('globalboost','GlobalBoost-Y','');
INSERT INTO BlockchainEntity VALUES('fedora-gold','Fedora Gold','');
INSERT INTO BlockchainEntity VALUES('petrachor','Petrachor','');
INSERT INTO BlockchainEntity VALUES('pinkcoin','Pinkcoin','');
INSERT INTO BlockchainEntity VALUES('bitmoney','BitMoney','');
INSERT INTO BlockchainEntity VALUES('uca','UCA Coin','');
INSERT INTO BlockchainEntity VALUES('litedoge','LiteDoge','');
INSERT INTO BlockchainEntity VALUES('kurrent','Kurrent','');
INSERT INTO BlockchainEntity VALUES('perkle','Perkle','');
INSERT INTO BlockchainEntity VALUES('infinite-launch','Infinite Launch','');
INSERT INTO BlockchainEntity VALUES('sundaeswap','SundaeSwap','');
INSERT INTO BlockchainEntity VALUES('tera-smart-money','TERA','');
INSERT INTO BlockchainEntity VALUES('worktips','Worktips','');
INSERT INTO BlockchainEntity VALUES('pump-coin','Pump Coin','');
INSERT INTO BlockchainEntity VALUES('blocknet','Blocknet','');
INSERT INTO BlockchainEntity VALUES('karbo','Karbo','');
INSERT INTO BlockchainEntity VALUES('the-champcoin','The ChampCoin','');
INSERT INTO BlockchainEntity VALUES('dipper-network','Dipper Network','');
INSERT INTO BlockchainEntity VALUES('xtrabytes','XTRABYTES','');
INSERT INTO BlockchainEntity VALUES('manateecoin','ManateeCoin','');
INSERT INTO BlockchainEntity VALUES('hospital-coin','Hospital Coin','');
INSERT INTO BlockchainEntity VALUES('hydra-token','Hydraledger','');
INSERT INTO BlockchainEntity VALUES('privcy','PRiVCY','');
INSERT INTO BlockchainEntity VALUES('kilo-shiba-inu','Kilo Shiba Inu','');
INSERT INTO BlockchainEntity VALUES('belrium','Belrium','');
INSERT INTO BlockchainEntity VALUES('timelockcoin','TimeLockCoin','');
INSERT INTO BlockchainEntity VALUES('lyfe','Lyfe','');
INSERT INTO BlockchainEntity VALUES('fantasy-gold','Fantasy Gold','');
INSERT INTO BlockchainEntity VALUES('playervsplayercoin','PlayerVsPlayerCoin','');
INSERT INTO BlockchainEntity VALUES('documentchain','Documentchain','');
INSERT INTO BlockchainEntity VALUES('mktcash','Mktcash','');
INSERT INTO BlockchainEntity VALUES('lightyears','Lightyears','');
INSERT INTO BlockchainEntity VALUES('pyrk','Pyrk','');
INSERT INTO BlockchainEntity VALUES('super8','Super8','');
INSERT INTO BlockchainEntity VALUES('tune','TUNE','');
INSERT INTO BlockchainEntity VALUES('agricoin','Agricoin','');
INSERT INTO BlockchainEntity VALUES('constellation-labs','Constellation','');
INSERT INTO BlockchainEntity VALUES('genesisx','GenesisX','');
INSERT INTO BlockchainEntity VALUES('concordium','Concordium','');
INSERT INTO BlockchainEntity VALUES('gleec-coin','Gleec Coin','');
INSERT INTO BlockchainEntity VALUES('shorty','Shorty','');
INSERT INTO BlockchainEntity VALUES('giletjaunecoin','GiletJauneCoin','');
INSERT INTO BlockchainEntity VALUES('acoin','Acoin','');
INSERT INTO BlockchainEntity VALUES('energy-web-token','Energy Web Token','');
INSERT INTO BlockchainEntity VALUES('paccoin','PAC Protocol','');
INSERT INTO BlockchainEntity VALUES('woodcoin','Woodcoin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-subsidium','Bitcoin Subsidium','');
INSERT INTO BlockchainEntity VALUES('bitcoin-lightning','Block-Logic','');
INSERT INTO BlockchainEntity VALUES('x-cash','X-CASH','');
INSERT INTO BlockchainEntity VALUES('pocketcoin','Pocketcoin','');
INSERT INTO BlockchainEntity VALUES('road','ROAD','');
INSERT INTO BlockchainEntity VALUES('gram','OpenGram','');
INSERT INTO BlockchainEntity VALUES('safeinsure','SafeInsure','');
INSERT INTO BlockchainEntity VALUES('tycoon-global','Tycoon Global','');
INSERT INTO BlockchainEntity VALUES('bitcicoin','Bitcicoin','');
INSERT INTO BlockchainEntity VALUES('artery','Artery','');
INSERT INTO BlockchainEntity VALUES('lynx','Lynx','');
INSERT INTO BlockchainEntity VALUES('digitalnote','DigitalNote','');
INSERT INTO BlockchainEntity VALUES('bitcoin-green','Bitcoin Green','');
INSERT INTO BlockchainEntity VALUES('jackpot','Jackpot','');
INSERT INTO BlockchainEntity VALUES('kucoin-shares','KuCoin Token','');
INSERT INTO BlockchainEntity VALUES('mobilecoin','MobileCoin','');
INSERT INTO BlockchainEntity VALUES('paws-funds','Paws Funds','');
INSERT INTO BlockchainEntity VALUES('npccoin','NPCcoin','');
INSERT INTO BlockchainEntity VALUES('dock','Dock','');
INSERT INTO BlockchainEntity VALUES('dynamic','Dynamic','');
INSERT INTO BlockchainEntity VALUES('helleniccoin','HNC Coin','');
INSERT INTO BlockchainEntity VALUES('magic-cube','Magic Cube Coin','');
INSERT INTO BlockchainEntity VALUES('ufocoin','Uniform Fiscal Object','');
INSERT INTO BlockchainEntity VALUES('suqa','SINOVATE','');
INSERT INTO BlockchainEntity VALUES('aitra','AITRA','');
INSERT INTO BlockchainEntity VALUES('tajcoin','TajCoin','');
INSERT INTO BlockchainEntity VALUES('cts-coin','Crypto Trading Solutions Coin','');
INSERT INTO BlockchainEntity VALUES('divi','Divi','');
INSERT INTO BlockchainEntity VALUES('milk-alliance','MiL.k Alliance','');
INSERT INTO BlockchainEntity VALUES('oasis-2','OASIS','');
INSERT INTO BlockchainEntity VALUES('goldblocks','GoldBlocks','');
INSERT INTO BlockchainEntity VALUES('unification','Unification','');
INSERT INTO BlockchainEntity VALUES('atheneum','Atheneum','');
INSERT INTO BlockchainEntity VALUES('gcn-coin','GCN Coin','');
INSERT INTO BlockchainEntity VALUES('crown','Crown','');
INSERT INTO BlockchainEntity VALUES('incoin','InCoin','');
INSERT INTO BlockchainEntity VALUES('kulupu','Kulupu','');
INSERT INTO BlockchainEntity VALUES('redbux','RedBUX','');
INSERT INTO BlockchainEntity VALUES('voytek-bear-coin','BEAR Coin','');
INSERT INTO BlockchainEntity VALUES('dash','Dash','');
INSERT INTO BlockchainEntity VALUES('worldcoin','WorldCoin','');
INSERT INTO BlockchainEntity VALUES('siacoin','Siacoin','');
INSERT INTO BlockchainEntity VALUES('whitecoin','Whitecoin','');
INSERT INTO BlockchainEntity VALUES('starname','Starname','');
INSERT INTO BlockchainEntity VALUES('pivx','PIVX','');
INSERT INTO BlockchainEntity VALUES('recovery-right-token','Recovery Right Token','');
INSERT INTO BlockchainEntity VALUES('vsync','Vsync','');
INSERT INTO BlockchainEntity VALUES('afro','Afro','');
INSERT INTO BlockchainEntity VALUES('monacoin','MonaCoin','');
INSERT INTO BlockchainEntity VALUES('etherinc','EtherInc','');
INSERT INTO BlockchainEntity VALUES('mdu','MDUKEY','');
INSERT INTO BlockchainEntity VALUES('digimoney','DigiMoney','');
INSERT INTO BlockchainEntity VALUES('karura','Karura','');
INSERT INTO BlockchainEntity VALUES('bonorum-coin','Bonorum','');
INSERT INTO BlockchainEntity VALUES('bitcore','BitCore','');
INSERT INTO BlockchainEntity VALUES('dash-diamond','Dash Diamond','');
INSERT INTO BlockchainEntity VALUES('birake','Birake','');
INSERT INTO BlockchainEntity VALUES('sakura','Sakura','');
INSERT INTO BlockchainEntity VALUES('verge','Verge','');
INSERT INTO BlockchainEntity VALUES('trinity','Trinity','');
INSERT INTO BlockchainEntity VALUES('deepbrain-chain','DeepBrain Chain','');
INSERT INTO BlockchainEntity VALUES('metamui','MetaMUI','');
INSERT INTO BlockchainEntity VALUES('livenodes','Livenodes','');
INSERT INTO BlockchainEntity VALUES('harmony','Harmony','');
INSERT INTO BlockchainEntity VALUES('cortex','Cortex','');
INSERT INTO BlockchainEntity VALUES('exchangecoin','ExchangeCoin','');
INSERT INTO BlockchainEntity VALUES('dogecash','DogeCash','');
INSERT INTO BlockchainEntity VALUES('pundi-x-nem','Pundi X NEM','');
INSERT INTO BlockchainEntity VALUES('arqma','ArQmA','');
INSERT INTO BlockchainEntity VALUES('masari','Masari','');
INSERT INTO BlockchainEntity VALUES('italo','Italo','');
INSERT INTO BlockchainEntity VALUES('classicbitcoin','ClassicBitcoin','');
INSERT INTO BlockchainEntity VALUES('phore','Phore','');
INSERT INTO BlockchainEntity VALUES('iridium','Iridium','');
INSERT INTO BlockchainEntity VALUES('gentarium','Gentarium','');
INSERT INTO BlockchainEntity VALUES('helix','Helix','');
INSERT INTO BlockchainEntity VALUES('collegicoin','Collegicoin','');
INSERT INTO BlockchainEntity VALUES('poolcoin','POOLCOIN','');
INSERT INTO BlockchainEntity VALUES('joys','JOYS','');
INSERT INTO BlockchainEntity VALUES('vankia-chain','Vankia Chain','');
INSERT INTO BlockchainEntity VALUES('fuzzballs','FuzzBalls','');
INSERT INTO BlockchainEntity VALUES('altmarkets-coin','Altmarkets Coin','');
INSERT INTO BlockchainEntity VALUES('eazypayza','EazyPayZa','');
INSERT INTO BlockchainEntity VALUES('digi-dinar','Digi Dinar','');
INSERT INTO BlockchainEntity VALUES('growthcoin','GrowthCoin','');
INSERT INTO BlockchainEntity VALUES('invoice-coin','Invoice Coin','');
INSERT INTO BlockchainEntity VALUES('diminutive-coin','Diminutive Coin','');
INSERT INTO BlockchainEntity VALUES('findora','Findora','');
INSERT INTO BlockchainEntity VALUES('metacoin','Metacoin','');
INSERT INTO BlockchainEntity VALUES('draken','Draken','');
INSERT INTO BlockchainEntity VALUES('mttcoin','MTTCoin','');
INSERT INTO BlockchainEntity VALUES('teslafunds','Transaction Service Fee','');
INSERT INTO BlockchainEntity VALUES('decimal','Decimal','');
INSERT INTO BlockchainEntity VALUES('bitcoin-cure','Byron','');
INSERT INTO BlockchainEntity VALUES('proud-money','Proud Money','');
INSERT INTO BlockchainEntity VALUES('globalchainz','GlobalChainZ','');
INSERT INTO BlockchainEntity VALUES('slothcoin','SlothCoin','');
INSERT INTO BlockchainEntity VALUES('iticoin','iTicoin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-private','Bitcoin Private','');
INSERT INTO BlockchainEntity VALUES('guapcoin','Guapcoin','');
INSERT INTO BlockchainEntity VALUES('abc-chain','ABC Chain','');
INSERT INTO BlockchainEntity VALUES('b2bcoin-2','B2Bcoin','');
INSERT INTO BlockchainEntity VALUES('defis','Defis','');
INSERT INTO BlockchainEntity VALUES('roxe','Roxe','');
INSERT INTO BlockchainEntity VALUES('shiden','Shiden Network','');
INSERT INTO BlockchainEntity VALUES('42-coin','42-coin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-confidential','Bitcoin Confidential','');
INSERT INTO BlockchainEntity VALUES('aos','AOS','');
INSERT INTO BlockchainEntity VALUES('swipp','Swipp','');
INSERT INTO BlockchainEntity VALUES('liber-coin','LIBER COIN','');
INSERT INTO BlockchainEntity VALUES('ethergem','EtherGem','');
INSERT INTO BlockchainEntity VALUES('harmonycoin','HarmonyCoin','');
INSERT INTO BlockchainEntity VALUES('solbit','SOLBIT','');
INSERT INTO BlockchainEntity VALUES('cybex','Cybex','');
INSERT INTO BlockchainEntity VALUES('qwertycoin','Qwertycoin','');
INSERT INTO BlockchainEntity VALUES('pakcoin','Pakcoin','');
INSERT INTO BlockchainEntity VALUES('lisk','Lisk','');
INSERT INTO BlockchainEntity VALUES('scootercoin','ScooterCoin','');
INSERT INTO BlockchainEntity VALUES('lightning-bitcoin','Lightning Bitcoin','');
INSERT INTO BlockchainEntity VALUES('beenode','Beenode','');
INSERT INTO BlockchainEntity VALUES('crave','Crave','');
INSERT INTO BlockchainEntity VALUES('fashion-coin','Fashion Coin','');
INSERT INTO BlockchainEntity VALUES('nerva','Nerva','');
INSERT INTO BlockchainEntity VALUES('genix','Genix','');
INSERT INTO BlockchainEntity VALUES('zero','Zero','');
INSERT INTO BlockchainEntity VALUES('bitcloud','Bitcloud','');
INSERT INTO BlockchainEntity VALUES('unobtanium','Unobtanium','');
INSERT INTO BlockchainEntity VALUES('rock-n-rain-coin','Rock N Rain Coin','');
INSERT INTO BlockchainEntity VALUES('smileycoin','Smileycoin','');
INSERT INTO BlockchainEntity VALUES('atheios','Atheios','');
INSERT INTO BlockchainEntity VALUES('eternal-oasis','Eternal Oasis','');
INSERT INTO BlockchainEntity VALUES('nervos-network','Nervos Network','');
INSERT INTO BlockchainEntity VALUES('futurocoin','FuturoCoin','');
INSERT INTO BlockchainEntity VALUES('ipx-token','Tachyon Protocol','');
INSERT INTO BlockchainEntity VALUES('ethdown','ETHDOWN','');
INSERT INTO BlockchainEntity VALUES('spots','Spots','');
INSERT INTO BlockchainEntity VALUES('xbit','Xbit','');
INSERT INTO BlockchainEntity VALUES('siaprime-coin','ScPrime','');
INSERT INTO BlockchainEntity VALUES('ballotbox','Ballotbox','');
INSERT INTO BlockchainEntity VALUES('flow','Flow','');
INSERT INTO BlockchainEntity VALUES('proshares-bitcoin-strategy-etf','ProShares Bitcoin Strategy ETF','');
INSERT INTO BlockchainEntity VALUES('litecoin-finance','Litecoin Finance','');
INSERT INTO BlockchainEntity VALUES('mao-zedong','Mao Zedong','');
INSERT INTO BlockchainEntity VALUES('escudonavacense','EscudoNavacense','');
INSERT INTO BlockchainEntity VALUES('blackcoin','BlackCoin','');
INSERT INTO BlockchainEntity VALUES('kobocoin','Kobocoin','');
INSERT INTO BlockchainEntity VALUES('megacoin','Megacoin','');
INSERT INTO BlockchainEntity VALUES('agrinovuscoin','AgriNovusCoin','');
INSERT INTO BlockchainEntity VALUES('game-frag','Game-Frag','');
INSERT INTO BlockchainEntity VALUES('ronpaulcoin','RonPaulCoin','');
INSERT INTO BlockchainEntity VALUES('robbocoach','RobboCoach','');
INSERT INTO BlockchainEntity VALUES('circleswap','CircleSwap','');
INSERT INTO BlockchainEntity VALUES('scriv','SCRIV','');
INSERT INTO BlockchainEntity VALUES('bloc-money','Bloc.Money','');
INSERT INTO BlockchainEntity VALUES('hyperexchange','HyperExchange','');
INSERT INTO BlockchainEntity VALUES('sparkle-coin','Sparkle Coin','');
INSERT INTO BlockchainEntity VALUES('touriva','Touriva','');
INSERT INTO BlockchainEntity VALUES('themis','Themis Network','');
INSERT INTO BlockchainEntity VALUES('deviantcoin','Deviant Coin','');
INSERT INTO BlockchainEntity VALUES('conceal','Conceal','');
INSERT INTO BlockchainEntity VALUES('phoenixcoin','Phoenixcoin','');
INSERT INTO BlockchainEntity VALUES('arcticcoin','Advanced Technology Coin','');
INSERT INTO BlockchainEntity VALUES('foincoin','Foin','');
INSERT INTO BlockchainEntity VALUES('moneybyte','MoneyByte','');
INSERT INTO BlockchainEntity VALUES('litecash','Litecash','');
INSERT INTO BlockchainEntity VALUES('motacoin','MotaCoin','');
INSERT INTO BlockchainEntity VALUES('zenzo','ZENZO','');
INSERT INTO BlockchainEntity VALUES('bring','Noir','');
INSERT INTO BlockchainEntity VALUES('galaxy-network','Galaxy Network','');
INSERT INTO BlockchainEntity VALUES('stronghands','StrongHands','');
INSERT INTO BlockchainEntity VALUES('fango','Fango','');
INSERT INTO BlockchainEntity VALUES('lethean','Lethean','');
INSERT INTO BlockchainEntity VALUES('dagger','Dagger','');
INSERT INTO BlockchainEntity VALUES('clams','Clams','');
INSERT INTO BlockchainEntity VALUES('equitrader','EquiTrader','');
INSERT INTO BlockchainEntity VALUES('animecoin','Animecoin','');
INSERT INTO BlockchainEntity VALUES('centrifuge','Centrifuge','');
INSERT INTO BlockchainEntity VALUES('utopia','Crypton','');
INSERT INTO BlockchainEntity VALUES('hive','Hive','');
INSERT INTO BlockchainEntity VALUES('solace-coin','Solace Coin','');
INSERT INTO BlockchainEntity VALUES('libonomy','Libonomy','');
INSERT INTO BlockchainEntity VALUES('sixeleven','SixEleven','');
INSERT INTO BlockchainEntity VALUES('russell-coin','RussellCoin','');
INSERT INTO BlockchainEntity VALUES('hedera-hashgraph','Hedera','');
INSERT INTO BlockchainEntity VALUES('governance-zil','governance ZIL','');
INSERT INTO BlockchainEntity VALUES('cannabiscoin','CannabisCoin','');
INSERT INTO BlockchainEntity VALUES('pchain','Plian','');
INSERT INTO BlockchainEntity VALUES('thought','Thought','');
INSERT INTO BlockchainEntity VALUES('soldo','Soldo','');
INSERT INTO BlockchainEntity VALUES('monk','Monk','');
INSERT INTO BlockchainEntity VALUES('quark','Quark','');
INSERT INTO BlockchainEntity VALUES('bitswift','Bitswift','');
INSERT INTO BlockchainEntity VALUES('spacecoin','Spacecoin','');
INSERT INTO BlockchainEntity VALUES('venox','Venox','');
INSERT INTO BlockchainEntity VALUES('zenad','Zenad','');
INSERT INTO BlockchainEntity VALUES('bitcoin-god','Bitcoin God','');
INSERT INTO BlockchainEntity VALUES('the-coop-network','The Coop Network','');
INSERT INTO BlockchainEntity VALUES('rilcoin','Rilcoin','');
INSERT INTO BlockchainEntity VALUES('metal-music-coin','Metal Music Coin','');
INSERT INTO BlockchainEntity VALUES('mindcoin','MindCoin','');
INSERT INTO BlockchainEntity VALUES('netcoin','Netcoin','');
INSERT INTO BlockchainEntity VALUES('nyerium','Nyerium','');
INSERT INTO BlockchainEntity VALUES('one-world-coin','One World Coin','');
INSERT INTO BlockchainEntity VALUES('marxcoin','MarxCoin','');
INSERT INTO BlockchainEntity VALUES('meconcash','Meconcash','');
INSERT INTO BlockchainEntity VALUES('akroma','Akroma','');
INSERT INTO BlockchainEntity VALUES('metaversex','MetaverseX','');
INSERT INTO BlockchainEntity VALUES('title-network','Bitcoin Clashic','');
INSERT INTO BlockchainEntity VALUES('antimony','Antimony','');
INSERT INTO BlockchainEntity VALUES('webchain','MintMe.com Coin','');
INSERT INTO BlockchainEntity VALUES('largo-coin','Largo Coin','');
INSERT INTO BlockchainEntity VALUES('zik-token','Ziktalk','');
INSERT INTO BlockchainEntity VALUES('raven-dark','Raven Dark','');
INSERT INTO BlockchainEntity VALUES('united-bitcoin','United Bitcoin','');
INSERT INTO BlockchainEntity VALUES('efin','eFIN','');
INSERT INTO BlockchainEntity VALUES('orao-network','ORAO Network','');
INSERT INTO BlockchainEntity VALUES('coral-swap','Coral Swap','');
INSERT INTO BlockchainEntity VALUES('suprenft','SupreNFT','');
INSERT INTO BlockchainEntity VALUES('xchainz','XChainZ','');
INSERT INTO BlockchainEntity VALUES('chives-coin','Chives Coin','');
INSERT INTO BlockchainEntity VALUES('waves-community-token','Waves Community Token','');
INSERT INTO BlockchainEntity VALUES('caica-coin','CAICA Coin','');
INSERT INTO BlockchainEntity VALUES('original-crypto-coin','The Universal Settlement Coin','');
INSERT INTO BlockchainEntity VALUES('koto','Koto','');
INSERT INTO BlockchainEntity VALUES('naka-bodhi-token','Naka Bodhi Token','');
INSERT INTO BlockchainEntity VALUES('emogi-network','EMOGI Network','');
INSERT INTO BlockchainEntity VALUES('qmcoin','QMCoin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-cash-sv','Bitcoin SV','');
INSERT INTO BlockchainEntity VALUES('kadena','Kadena','');
INSERT INTO BlockchainEntity VALUES('iostoken','IOST','');
INSERT INTO BlockchainEntity VALUES('conflux-token','Conflux','');
INSERT INTO BlockchainEntity VALUES('reddcoin','Reddcoin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-cash','Bitcoin Cash','');
INSERT INTO BlockchainEntity VALUES('temtem','Temtum','');
INSERT INTO BlockchainEntity VALUES('cryptoverificationcoin','CryptoVerificationCoin','');
INSERT INTO BlockchainEntity VALUES('filecash','Filecash','');
INSERT INTO BlockchainEntity VALUES('bitkub-coin','Bitkub Coin','');
INSERT INTO BlockchainEntity VALUES('sora','Sora','https://sorascan.com/sora-mainnet/asset/$ref');
INSERT INTO BlockchainEntity VALUES('energi','Energi','');
INSERT INTO BlockchainEntity VALUES('harmony-shard-0','Harmony Shard 0','https://explorer.harmony.one/address/$ref');
INSERT INTO BlockchainEntity VALUES('akash-network','Akash Network','');
INSERT INTO BlockchainEntity VALUES('thundercore','thundercore','');
INSERT INTO BlockchainEntity VALUES('cerium','Cerium','');
INSERT INTO BlockchainEntity VALUES('iris-network','IRISnet','');
INSERT INTO BlockchainEntity VALUES('aspire','Aspire','');
INSERT INTO BlockchainEntity VALUES('pengolincoin','PengolinCoin','');
INSERT INTO BlockchainEntity VALUES('echosoracoin','EchoSoraCoin','');
INSERT INTO BlockchainEntity VALUES('allive','Allive','');
INSERT INTO BlockchainEntity VALUES('sonocoin','SonoCoin','');
INSERT INTO BlockchainEntity VALUES('welups-blockchain','Welups Blockchain','');
INSERT INTO BlockchainEntity VALUES('theholyrogercoin','TheHolyRogerCoin','');
INSERT INTO BlockchainEntity VALUES('guncoin','Guncoin','');
INSERT INTO BlockchainEntity VALUES('nestegg-coin','NestEgg Coin','');
INSERT INTO BlockchainEntity VALUES('vindax-coin','VinDax Coin','');
INSERT INTO BlockchainEntity VALUES('polkadot','Polkadot','');
INSERT INTO BlockchainEntity VALUES('aidos-kuneen','Aidos Kuneen','');
INSERT INTO BlockchainEntity VALUES('litecoin-cash','Litecoin Cash','');
INSERT INTO BlockchainEntity VALUES('witnet','Witnet','');
INSERT INTO BlockchainEntity VALUES('rutheneum','Rutheneum','');
INSERT INTO BlockchainEntity VALUES('medibloc','Medibloc','');
INSERT INTO BlockchainEntity VALUES('five-balance','Fivebalance Coin','');
INSERT INTO BlockchainEntity VALUES('trittium','Trittium','');
INSERT INTO BlockchainEntity VALUES('cirrus','Cirrus','');
INSERT INTO BlockchainEntity VALUES('social-send','Social Send','');
INSERT INTO BlockchainEntity VALUES('bitcoinz','BitcoinZ','');
INSERT INTO BlockchainEntity VALUES('utip','uTip','');
INSERT INTO BlockchainEntity VALUES('gold-poker','Gold Poker','');
INSERT INTO BlockchainEntity VALUES('linda','Metrix Coin','');
INSERT INTO BlockchainEntity VALUES('imagecash','ImageCash','');
INSERT INTO BlockchainEntity VALUES('observer-coin','OBSERVER Coin','');
INSERT INTO BlockchainEntity VALUES('cutcoin','CUTcoin','');
INSERT INTO BlockchainEntity VALUES('integritee','Integritee','');
INSERT INTO BlockchainEntity VALUES('uniworld','UniWorld','');
INSERT INTO BlockchainEntity VALUES('hertz-network','Hertz Network','');
INSERT INTO BlockchainEntity VALUES('fydcoin','FYDcoin','');
INSERT INTO BlockchainEntity VALUES('poa-network','POA Network','');
INSERT INTO BlockchainEntity VALUES('hyperstake','HyperStake','');
INSERT INTO BlockchainEntity VALUES('zrcoin','ZrCoin','');
INSERT INTO BlockchainEntity VALUES('experiencecoin','ExperienceCoin','');
INSERT INTO BlockchainEntity VALUES('daps-token','DAPS Coin','');
INSERT INTO BlockchainEntity VALUES('trollcoin','Trollcoin','');
INSERT INTO BlockchainEntity VALUES('bitica-coin','BITICA COIN','');
INSERT INTO BlockchainEntity VALUES('bluecoin','Bluecoin','');
INSERT INTO BlockchainEntity VALUES('zillioncoin','ZillionCoin','');
INSERT INTO BlockchainEntity VALUES('xrpalike-gene','Xrpalike Gene','');
INSERT INTO BlockchainEntity VALUES('spice','Spice Token','');
INSERT INTO BlockchainEntity VALUES('kevacoin','Kevacoin','');
INSERT INTO BlockchainEntity VALUES('kepler-network','Kepler Network','');
INSERT INTO BlockchainEntity VALUES('kyanite','Kyanite','');
INSERT INTO BlockchainEntity VALUES('coalculus','Coalculus','');
INSERT INTO BlockchainEntity VALUES('cirquity','Cirquity','');
INSERT INTO BlockchainEntity VALUES('litecoinz','LitecoinZ','');
INSERT INTO BlockchainEntity VALUES('eboost','eBoost','');
INSERT INTO BlockchainEntity VALUES('ecc','ECC','');
INSERT INTO BlockchainEntity VALUES('decentralway','Decentralway','');
INSERT INTO BlockchainEntity VALUES('halcyon','Halcyon','');
INSERT INTO BlockchainEntity VALUES('bitcoinmoney','BitcoinMoney','');
INSERT INTO BlockchainEntity VALUES('osmiumcoin','OsmiumCoin','');
INSERT INTO BlockchainEntity VALUES('ovato','Ovato','');
INSERT INTO BlockchainEntity VALUES('schillingcoin','Schilling-Coin','');
INSERT INTO BlockchainEntity VALUES('version','Version','');
INSERT INTO BlockchainEntity VALUES('bellcoin','Bellcoin','');
INSERT INTO BlockchainEntity VALUES('motocoin','Motocoin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-plus','Bitcoin Plus','');
INSERT INTO BlockchainEntity VALUES('omotenashicoin','OmotenashiCoin','');
INSERT INTO BlockchainEntity VALUES('salus','SaluS','');
INSERT INTO BlockchainEntity VALUES('moments','Moments Market','');
INSERT INTO BlockchainEntity VALUES('datahighway','DataHighway','');
INSERT INTO BlockchainEntity VALUES('xenios','Xenios','');
INSERT INTO BlockchainEntity VALUES('safepe','SafePe','');
INSERT INTO BlockchainEntity VALUES('sparks','SparksPay','');
INSERT INTO BlockchainEntity VALUES('treasure-sl','Treasure SL','');
INSERT INTO BlockchainEntity VALUES('ghost-by-mcafee','Ghost','');
INSERT INTO BlockchainEntity VALUES('luxcoin','LUXCoin','');
INSERT INTO BlockchainEntity VALUES('ratecoin','Ratecoin','');
INSERT INTO BlockchainEntity VALUES('ride-my-car','Ride My Car','');
INSERT INTO BlockchainEntity VALUES('x-protocol','X Protocol','');
INSERT INTO BlockchainEntity VALUES('fedoracoin','Fedoracoin','');
INSERT INTO BlockchainEntity VALUES('x42-protocol','X42 Protocol','');
INSERT INTO BlockchainEntity VALUES('alaya','Alaya','');
INSERT INTO BlockchainEntity VALUES('californium','Californium','');
INSERT INTO BlockchainEntity VALUES('oracolxor','Oracolxor','');
INSERT INTO BlockchainEntity VALUES('aryacoin','Aryacoin','');
INSERT INTO BlockchainEntity VALUES('btf','Bitcoin Faith','');
INSERT INTO BlockchainEntity VALUES('piasa','PIASA','');
INSERT INTO BlockchainEntity VALUES('solaris','Solaris','');
INSERT INTO BlockchainEntity VALUES('dynamo-coin','Dynamo Coin','');
INSERT INTO BlockchainEntity VALUES('bitwhite','BitWhite','');
INSERT INTO BlockchainEntity VALUES('allsafe','AllSafe','');
INSERT INTO BlockchainEntity VALUES('evil-coin','Evil Coin','');
INSERT INTO BlockchainEntity VALUES('bolivarcoin','Bolivarcoin','');
INSERT INTO BlockchainEntity VALUES('rito','Rito','');
INSERT INTO BlockchainEntity VALUES('postcoin','PostCoin','');
INSERT INTO BlockchainEntity VALUES('pos-coin','POS Coin','');
INSERT INTO BlockchainEntity VALUES('dascoin','GreenPower','');
INSERT INTO BlockchainEntity VALUES('bitgesell','Bitgesell','');
INSERT INTO BlockchainEntity VALUES('arrow','Arrow','');
INSERT INTO BlockchainEntity VALUES('gold-secured-currency','Gold Secured Currency','');
INSERT INTO BlockchainEntity VALUES('bitcoin-token','BitcoinToken','');
INSERT INTO BlockchainEntity VALUES('rowan-coin','Rowan Coin','');
INSERT INTO BlockchainEntity VALUES('blockstack','Stacks','');
INSERT INTO BlockchainEntity VALUES('counosx','CounosX','');
INSERT INTO BlockchainEntity VALUES('takamaka-green-coin','Takamaka Green Coin','');
INSERT INTO BlockchainEntity VALUES('bitblocks-project','BitBlocks','');
INSERT INTO BlockchainEntity VALUES('bitmark','Bitmark','');
INSERT INTO BlockchainEntity VALUES('ibithub','iBitHub','');
INSERT INTO BlockchainEntity VALUES('ponzicoin','PonziCoin','');
INSERT INTO BlockchainEntity VALUES('renrenbit','Renrenbit','');
INSERT INTO BlockchainEntity VALUES('beyondcoin','Beyondcoin','');
INSERT INTO BlockchainEntity VALUES('microbitcoin','MicroBitcoin','');
INSERT INTO BlockchainEntity VALUES('bitgem','Bitgem','');
INSERT INTO BlockchainEntity VALUES('chia','Chia','');
INSERT INTO BlockchainEntity VALUES('lunes','Lunes','');
INSERT INTO BlockchainEntity VALUES('pascalcoin','Pascal','');
INSERT INTO BlockchainEntity VALUES('lightstreams','Lightstreams Photon','');
INSERT INTO BlockchainEntity VALUES('rizon','Rizon','');
INSERT INTO BlockchainEntity VALUES('hempcoin-thc','Hempcoin','');
INSERT INTO BlockchainEntity VALUES('stakecube','Stakecube','');
INSERT INTO BlockchainEntity VALUES('suvereno','Suvereno','');
INSERT INTO BlockchainEntity VALUES('imagecoin','ImageCoin','');
INSERT INTO BlockchainEntity VALUES('sandego','SanDeGo','');
INSERT INTO BlockchainEntity VALUES('bit-ecological-digital','Bit Ecological Digital','');
INSERT INTO BlockchainEntity VALUES('mimblewimblecoin','MimbleWimbleCoin','');
INSERT INTO BlockchainEntity VALUES('alibabacoin','ABBC','');
INSERT INTO BlockchainEntity VALUES('kava-swap','Kava Swap','');
INSERT INTO BlockchainEntity VALUES('dequant','Dequant','');
INSERT INTO BlockchainEntity VALUES('donnie-finance','Donnie Finance','');
INSERT INTO BlockchainEntity VALUES('iocoin','I/O Coin','');
INSERT INTO BlockchainEntity VALUES('wab-network','BAW Network','');
INSERT INTO BlockchainEntity VALUES('prizm','Prizm','');
INSERT INTO BlockchainEntity VALUES('football-coin','Football Coin','');
INSERT INTO BlockchainEntity VALUES('tune-token','TUNE TOKEN','');
INSERT INTO BlockchainEntity VALUES('vaperscoin','VapersCoin','');
INSERT INTO BlockchainEntity VALUES('new-power-coin','New Power Coin','');
INSERT INTO BlockchainEntity VALUES('symbol','Symbol','');
INSERT INTO BlockchainEntity VALUES('mktcoin','MktCoin','');
INSERT INTO BlockchainEntity VALUES('minergate-token','MinerGate Token','');
INSERT INTO BlockchainEntity VALUES('philscurrency','Digiwage','');
INSERT INTO BlockchainEntity VALUES('mintcoin','Mintcoin','');
INSERT INTO BlockchainEntity VALUES('yocoin','yocoin','');
INSERT INTO BlockchainEntity VALUES('zcore','ZCore','');
INSERT INTO BlockchainEntity VALUES('microcoin','MicroCoin','');
INSERT INTO BlockchainEntity VALUES('mooncoin','Mooncoin','');
INSERT INTO BlockchainEntity VALUES('sprint-coin','Sprint Coin','');
INSERT INTO BlockchainEntity VALUES('tnc-coin','TNC Coin','');
INSERT INTO BlockchainEntity VALUES('bsha3','BSHA3','');
INSERT INTO BlockchainEntity VALUES('capital-x-cell','CAPITAL X CELL','');
INSERT INTO BlockchainEntity VALUES('expanse','Expanse','');
INSERT INTO BlockchainEntity VALUES('gxchain','GXChain','');
INSERT INTO BlockchainEntity VALUES('martkist','Martkist','');
INSERT INTO BlockchainEntity VALUES('junsonmingchancoin','Junsonmingchancoin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-ultra','BitcoinUltra','');
INSERT INTO BlockchainEntity VALUES('magpiecoin','MagpieCoin','');
INSERT INTO BlockchainEntity VALUES('ngin','Ngin','');
INSERT INTO BlockchainEntity VALUES('valuto','Valuto','');
INSERT INTO BlockchainEntity VALUES('cream','Creamcoin','');
INSERT INTO BlockchainEntity VALUES('netm','Netm','');
INSERT INTO BlockchainEntity VALUES('beacon','Beacon','');
INSERT INTO BlockchainEntity VALUES('letitride','LetItRide','');
INSERT INTO BlockchainEntity VALUES('fruits','Fruits','');
INSERT INTO BlockchainEntity VALUES('emrals','Emrals','');
INSERT INTO BlockchainEntity VALUES('deracoin','Deracoin','');
INSERT INTO BlockchainEntity VALUES('nextdao','NextDAO','');
INSERT INTO BlockchainEntity VALUES('payment-coin','Payment Coin','');
INSERT INTO BlockchainEntity VALUES('certurium','Certurium','');
INSERT INTO BlockchainEntity VALUES('bitcoinx-2','BitcoinXGames','');
INSERT INTO BlockchainEntity VALUES('zealium','Zealium','');
INSERT INTO BlockchainEntity VALUES('vcash','Vcash','');
INSERT INTO BlockchainEntity VALUES('secure-cash','Secure Cash','');
INSERT INTO BlockchainEntity VALUES('fanaticos-cash','Fanáticos Cash','');
INSERT INTO BlockchainEntity VALUES('futurescoin','FuturesCoin','');
INSERT INTO BlockchainEntity VALUES('filecoin','Filecoin','');
INSERT INTO BlockchainEntity VALUES('helium','Helium','');
INSERT INTO BlockchainEntity VALUES('ecash','eCash','');
INSERT INTO BlockchainEntity VALUES('arweave','Arweave','');
INSERT INTO BlockchainEntity VALUES('mina-protocol','Mina Protocol','');
INSERT INTO BlockchainEntity VALUES('bytecoin','Bytecoin','');
INSERT INTO BlockchainEntity VALUES('marscoin','Marscoin','');
INSERT INTO BlockchainEntity VALUES('apollo','Apollo','');
INSERT INTO BlockchainEntity VALUES('vertcoin','Vertcoin','');
INSERT INTO BlockchainEntity VALUES('siaclassic','SiaClassic','');
INSERT INTO BlockchainEntity VALUES('callisto','Callisto Network','');
INSERT INTO BlockchainEntity VALUES('hawaii-coin','Hawaii Coin','');
INSERT INTO BlockchainEntity VALUES('metahash','#MetaHash','');
INSERT INTO BlockchainEntity VALUES('aeon','Aeon','');
INSERT INTO BlockchainEntity VALUES('v-systems','V.SYSTEMS','');
INSERT INTO BlockchainEntity VALUES('espers','Espers','');
INSERT INTO BlockchainEntity VALUES('putincoin','PutinCoin','');
INSERT INTO BlockchainEntity VALUES('zeitcoin','Zeitcoin','');
INSERT INTO BlockchainEntity VALUES('sumokoin','Sumokoin','');
INSERT INTO BlockchainEntity VALUES('g999','G999','');
INSERT INTO BlockchainEntity VALUES('mine-network','MINE Network','');
INSERT INTO BlockchainEntity VALUES('vidulum','Vidulum','');
INSERT INTO BlockchainEntity VALUES('hashgard','Hashgard','');
INSERT INTO BlockchainEntity VALUES('0cash','0cash','');
INSERT INTO BlockchainEntity VALUES('ixcoin','Ixcoin','');
INSERT INTO BlockchainEntity VALUES('quantis','Quantis','');
INSERT INTO BlockchainEntity VALUES('bata','Bata','');
INSERT INTO BlockchainEntity VALUES('plusonecoin','PlusOneCoin','');
INSERT INTO BlockchainEntity VALUES('bigdata-cash','BigdataCash','');
INSERT INTO BlockchainEntity VALUES('deutsche-emark','Deutsche eMark','');
INSERT INTO BlockchainEntity VALUES('petrodollar','PetroDollar','');
INSERT INTO BlockchainEntity VALUES('luckchain','LuckChain','');
INSERT INTO BlockchainEntity VALUES('ultragate','Ultragate','');
INSERT INTO BlockchainEntity VALUES('scolcoin','Scolcoin','');
INSERT INTO BlockchainEntity VALUES('compound-coin','Compound Coin','');
INSERT INTO BlockchainEntity VALUES('melonheadsprotocol','MelonHeadSProtocol','');
INSERT INTO BlockchainEntity VALUES('orlycoin','Orlycoin','');
INSERT INTO BlockchainEntity VALUES('oc-protocol','OC Protocol','');
INSERT INTO BlockchainEntity VALUES('starchain','StarChain','');
INSERT INTO BlockchainEntity VALUES('haroldcoin','Haroldcoin','');
INSERT INTO BlockchainEntity VALUES('sproutsextreme','SproutsExtreme','');
INSERT INTO BlockchainEntity VALUES('mnpostree','MNPoSTree','');
INSERT INTO BlockchainEntity VALUES('sibcoin','SIBCoin','');
INSERT INTO BlockchainEntity VALUES('freecash','Freecash','');
INSERT INTO BlockchainEntity VALUES('excelon','Excelon','');
INSERT INTO BlockchainEntity VALUES('ripple','XRP','');
INSERT INTO BlockchainEntity VALUES('radium','Validity','');
INSERT INTO BlockchainEntity VALUES('trezarcoin','TrezarCoin','');
INSERT INTO BlockchainEntity VALUES('zerozed','Zerozed','');
INSERT INTO BlockchainEntity VALUES('megatech','Megatech','');
INSERT INTO BlockchainEntity VALUES('goldkash','GoldKash','');
INSERT INTO BlockchainEntity VALUES('cloakcoin','Cloakcoin','');
INSERT INTO BlockchainEntity VALUES('ravencoin-classic','Ravencoin Classic','');
INSERT INTO BlockchainEntity VALUES('poc-blockchain','POC Blockchain','');
INSERT INTO BlockchainEntity VALUES('ecochain','Ecochain','');
INSERT INTO BlockchainEntity VALUES('peseta-digital','Peseta Digital','');
INSERT INTO BlockchainEntity VALUES('carboncoin','Carboncoin','');
INSERT INTO BlockchainEntity VALUES('safecapital','SafeCapital','');
INSERT INTO BlockchainEntity VALUES('gsmcoin','GSMcoin','');
INSERT INTO BlockchainEntity VALUES('myce','MYCE','');
INSERT INTO BlockchainEntity VALUES('impleum','Impleum','');
INSERT INTO BlockchainEntity VALUES('xtendcash','XtendCash','');
INSERT INTO BlockchainEntity VALUES('mobile-crypto-pay-coin','Mobile Crypto Pay Coin','');
INSERT INTO BlockchainEntity VALUES('sx-network','sx-network','');
INSERT INTO BlockchainEntity VALUES('manna','Manna','');
INSERT INTO BlockchainEntity VALUES('electric-cash','Electric Cash','');
INSERT INTO BlockchainEntity VALUES('global-smart-asset','Global Smart Asset','');
INSERT INTO BlockchainEntity VALUES('darma-cash','Darma Cash','');
INSERT INTO BlockchainEntity VALUES('stellite','Scala','');
INSERT INTO BlockchainEntity VALUES('geysercoin','GeyserCoin','');
INSERT INTO BlockchainEntity VALUES('spartancoin','SpartanCoin','');
INSERT INTO BlockchainEntity VALUES('infinium','Infinium','');
INSERT INTO BlockchainEntity VALUES('appics','Appics','');
INSERT INTO BlockchainEntity VALUES('cricket-foundation','Cricket Foundation','');
INSERT INTO BlockchainEntity VALUES('miamicoin','MiamiCoin','');
INSERT INTO BlockchainEntity VALUES('meter-stable','Meter Stable','');
INSERT INTO BlockchainEntity VALUES('viacoin','Viacoin','');
INSERT INTO BlockchainEntity VALUES('bitconnect','Bitconnect','');
INSERT INTO BlockchainEntity VALUES('zclassic','Zclassic','');
INSERT INTO BlockchainEntity VALUES('bittube','BitTube','');
INSERT INTO BlockchainEntity VALUES('terra','Terra','');
INSERT INTO BlockchainEntity VALUES('bullion','Bullion','');
INSERT INTO BlockchainEntity VALUES('monetaryunit','MonetaryUnit','');
INSERT INTO BlockchainEntity VALUES('huobi-token','Huobi ECO Chain Mainnet','https://hecoinfo.com/token/$ref');
INSERT INTO BlockchainEntity VALUES('yunex','YunEx Yun Token','');
INSERT INTO BlockchainEntity VALUES('blast','BLAST','');
INSERT INTO BlockchainEntity VALUES('wavesgo','WavesGo','');
INSERT INTO BlockchainEntity VALUES('ignition','Ignition','');
INSERT INTO BlockchainEntity VALUES('wechain-coin','WeChain Coin','');
INSERT INTO BlockchainEntity VALUES('bitshares','BitShares','');
INSERT INTO BlockchainEntity VALUES('rise','Rise','');
INSERT INTO BlockchainEntity VALUES('usd-sports','USD Sports','');
INSERT INTO BlockchainEntity VALUES('elya','Elya','');
INSERT INTO BlockchainEntity VALUES('niobio-cash','Niobio','');
INSERT INTO BlockchainEntity VALUES('zumcoin','ZumCoin','');
INSERT INTO BlockchainEntity VALUES('bowscoin','BowsCoin','');
INSERT INTO BlockchainEntity VALUES('near','Near','');
INSERT INTO BlockchainEntity VALUES('xtrm','XTRM','');
INSERT INTO BlockchainEntity VALUES('bantu','Bantu','');
INSERT INTO BlockchainEntity VALUES('project-x','Project-X','');
INSERT INTO BlockchainEntity VALUES('cryptocean','Cryptocean','');
INSERT INTO BlockchainEntity VALUES('daikicoin','Daikicoin','');
INSERT INTO BlockchainEntity VALUES('wxcoin','WXCOINS','');
INSERT INTO BlockchainEntity VALUES('pay-coin','Paycoin','');
INSERT INTO BlockchainEntity VALUES('thinkium','Thinkium','');
INSERT INTO BlockchainEntity VALUES('axel','AXEL','');
INSERT INTO BlockchainEntity VALUES('quantum-resistant-ledger','Quantum Resistant Ledger','');
INSERT INTO BlockchainEntity VALUES('neblio','Neblio','');
INSERT INTO BlockchainEntity VALUES('credits','CREDITS','');
INSERT INTO BlockchainEntity VALUES('dingocoin','Dingocoin','');
INSERT INTO BlockchainEntity VALUES('atromg8','ATROMG8','');
INSERT INTO BlockchainEntity VALUES('vipstarcoin','VIPSTARCOIN','');
INSERT INTO BlockchainEntity VALUES('atbcoin','ATBCoin','');
INSERT INTO BlockchainEntity VALUES('bitsum','Matka','');
INSERT INTO BlockchainEntity VALUES('greenpay-coin','GreenPay Coin','');
INSERT INTO BlockchainEntity VALUES('ibank','iBank','');
INSERT INTO BlockchainEntity VALUES('tagrcoin','TAGRcoin','');
INSERT INTO BlockchainEntity VALUES('ti-value','Ti-Value','');
INSERT INTO BlockchainEntity VALUES('fibos','FIBOS','');
INSERT INTO BlockchainEntity VALUES('bitconnectx-genesis','BCCXGenesis','');
INSERT INTO BlockchainEntity VALUES('uplexa','uPlexa','');
INSERT INTO BlockchainEntity VALUES('bitcoin-scrypt','Bitcoin Scrypt','');
INSERT INTO BlockchainEntity VALUES('apr-coin','APR Coin','');
INSERT INTO BlockchainEntity VALUES('intucoin','INTUCoin','');
INSERT INTO BlockchainEntity VALUES('sumcoin','Sumcoin','');
INSERT INTO BlockchainEntity VALUES('sexcoin','Sexcoin','');
INSERT INTO BlockchainEntity VALUES('exclusivecoin','ExclusiveCoin','');
INSERT INTO BlockchainEntity VALUES('lucent','Lucent','');
INSERT INTO BlockchainEntity VALUES('orbitcoin','Orbitcoin','');
INSERT INTO BlockchainEntity VALUES('bitcoinx','BitcoinX','');
INSERT INTO BlockchainEntity VALUES('crowdclassic','CRowdCLassic','');
INSERT INTO BlockchainEntity VALUES('artbyte','ArtByte','');
INSERT INTO BlockchainEntity VALUES('betxoin','Betxoin','');
INSERT INTO BlockchainEntity VALUES('shilling','Shilling','');
INSERT INTO BlockchainEntity VALUES('elrond-erd-2','Elrond','');
INSERT INTO BlockchainEntity VALUES('decred','Decred','');
INSERT INTO BlockchainEntity VALUES('bitcoin-2','Bitcoin 2','');
INSERT INTO BlockchainEntity VALUES('auroracoin','Auroracoin','');
INSERT INTO BlockchainEntity VALUES('veil','VEIL','');
INSERT INTO BlockchainEntity VALUES('gulden','Gulden','');
INSERT INTO BlockchainEntity VALUES('sugarchain','Sugarchain','');
INSERT INTO BlockchainEntity VALUES('opalcoin','Opalcoin','');
INSERT INTO BlockchainEntity VALUES('shield','SHIELD','');
INSERT INTO BlockchainEntity VALUES('trust-wallet-token','Trust Wallet Token','');
INSERT INTO BlockchainEntity VALUES('ark','Ark','');
INSERT INTO BlockchainEntity VALUES('freicoin','Freicoin','');
INSERT INTO BlockchainEntity VALUES('alloy-project','Alloy Project','');
INSERT INTO BlockchainEntity VALUES('ravencoin','Ravencoin','');
INSERT INTO BlockchainEntity VALUES('powerbalt','PowerBalt','');
INSERT INTO BlockchainEntity VALUES('amz-coin','AMZ Coin','');
INSERT INTO BlockchainEntity VALUES('eth3s','ETH3S','');
INSERT INTO BlockchainEntity VALUES('backpacker-coin','BackPacker Coin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-instant','Bitcoin Instant','');
INSERT INTO BlockchainEntity VALUES('vip-coin','Vip Coin','');
INSERT INTO BlockchainEntity VALUES('kcash','Kcash','');
INSERT INTO BlockchainEntity VALUES('hive_dollar','Hive Dollar','');
INSERT INTO BlockchainEntity VALUES('haven','Haven','');
INSERT INTO BlockchainEntity VALUES('hydra','Hydra','');
INSERT INTO BlockchainEntity VALUES('hathor','Hathor','');
INSERT INTO BlockchainEntity VALUES('binarium','Binarium','');
INSERT INTO BlockchainEntity VALUES('emercoin','EmerCoin','');
INSERT INTO BlockchainEntity VALUES('merebel','Merebel','');
INSERT INTO BlockchainEntity VALUES('empow','Empow','');
INSERT INTO BlockchainEntity VALUES('paymastercoin','PayMasterCoin','');
INSERT INTO BlockchainEntity VALUES('gasp','gAsp','');
INSERT INTO BlockchainEntity VALUES('bitcoin-hot','Bitcoin Hot','');
INSERT INTO BlockchainEntity VALUES('litecoin','Litecoin','');
INSERT INTO BlockchainEntity VALUES('stipend','Stipend','');
INSERT INTO BlockchainEntity VALUES('joulecoin','Joulecoin','');
INSERT INTO BlockchainEntity VALUES('xuez','Xuez Coin','');
INSERT INTO BlockchainEntity VALUES('high-performance-blockchain','High Performance Blockchain','');
INSERT INTO BlockchainEntity VALUES('eth2-staking-by-poolx','Eth 2.0 Staking by Pool-X','');
INSERT INTO BlockchainEntity VALUES('ascension','Ascension','');
INSERT INTO BlockchainEntity VALUES('wayawolfcoin','WayaWolfCoin','');
INSERT INTO BlockchainEntity VALUES('binanceidr','BIDR','');
INSERT INTO BlockchainEntity VALUES('okcash','OKCash','');
INSERT INTO BlockchainEntity VALUES('sphere','Sphere','');
INSERT INTO BlockchainEntity VALUES('paycon-token','Paycon Token','');
INSERT INTO BlockchainEntity VALUES('namecoin','Namecoin','');
INSERT INTO BlockchainEntity VALUES('lucy','LUCY','');
INSERT INTO BlockchainEntity VALUES('bitstake','BitStake','');
INSERT INTO BlockchainEntity VALUES('dogecoin','Dogecoin','');
INSERT INTO BlockchainEntity VALUES('steem-dollars','Steem Dollars','');
INSERT INTO BlockchainEntity VALUES('mass','MASS','');
INSERT INTO BlockchainEntity VALUES('vexanium','Vexanium','');
INSERT INTO BlockchainEntity VALUES('snowblossom','SnowBlossom','');
INSERT INTO BlockchainEntity VALUES('zonecoin','Zonecoin','');
INSERT INTO BlockchainEntity VALUES('remita-coin','Remita Coin','');
INSERT INTO BlockchainEntity VALUES('crypto-sports','Crypto Sports','');
INSERT INTO BlockchainEntity VALUES('aion','Aion','');
INSERT INTO BlockchainEntity VALUES('monero','Monero','');
INSERT INTO BlockchainEntity VALUES('beldex','Beldex','');
INSERT INTO BlockchainEntity VALUES('iota','IOTA','');
INSERT INTO BlockchainEntity VALUES('flits','Flits','');
INSERT INTO BlockchainEntity VALUES('deeponion','DeepOnion','');
INSERT INTO BlockchainEntity VALUES('litebar','LiteBar','');
INSERT INTO BlockchainEntity VALUES('safe-coin-2','SafeCoin','');
INSERT INTO BlockchainEntity VALUES('new-bitshares','New BitShares','');
INSERT INTO BlockchainEntity VALUES('nervenetwork','NerveNetwork','');
INSERT INTO BlockchainEntity VALUES('nano','Nano','');
INSERT INTO BlockchainEntity VALUES('tezos','Tezos','');
INSERT INTO BlockchainEntity VALUES('tomochain','TomoChain','https://scan.tomochain.com/tokens/$ref');
INSERT INTO BlockchainEntity VALUES('fio-protocol','FIO Protocol','');
INSERT INTO BlockchainEntity VALUES('globalcoin','GlobalCoin','');
INSERT INTO BlockchainEntity VALUES('raptoreum','Raptoreum','');
INSERT INTO BlockchainEntity VALUES('steem','Steem','');
INSERT INTO BlockchainEntity VALUES('darkpaycoin','DARK','');
INSERT INTO BlockchainEntity VALUES('diamond','Diamond','');
INSERT INTO BlockchainEntity VALUES('mchain','Mchain','');
INSERT INTO BlockchainEntity VALUES('cashhand','Cashhand','');
INSERT INTO BlockchainEntity VALUES('404','404','');
INSERT INTO BlockchainEntity VALUES('ddmcoin','DDMCoin','');
INSERT INTO BlockchainEntity VALUES('dappercoin','DapperCoin','');
INSERT INTO BlockchainEntity VALUES('bare','BARE','');
INSERT INTO BlockchainEntity VALUES('hymnode','Hymnode','');
INSERT INTO BlockchainEntity VALUES('dinastycoin','Dinastycoin','');
INSERT INTO BlockchainEntity VALUES('nexdax','NexDAX','');
INSERT INTO BlockchainEntity VALUES('htmlcoin','HTMLCOIN','');
INSERT INTO BlockchainEntity VALUES('electronic-pk-chain','Electronic PK Chain','');
INSERT INTO BlockchainEntity VALUES('curecoin','Curecoin','');
INSERT INTO BlockchainEntity VALUES('simple-masternode-coin','Simple Masternode Coin','');
INSERT INTO BlockchainEntity VALUES('medic-coin','Medic Coin','');
INSERT INTO BlockchainEntity VALUES('kashhcoin','Kashhcoin','');
INSERT INTO BlockchainEntity VALUES('sono','SONO','');
INSERT INTO BlockchainEntity VALUES('einsteinium','Einsteinium','');
INSERT INTO BlockchainEntity VALUES('lightningcoin','LightningCoin','');
INSERT INTO BlockchainEntity VALUES('fireants','FireAnts','');
INSERT INTO BlockchainEntity VALUES('dexa-coin','DEXA COIN','');
INSERT INTO BlockchainEntity VALUES('litecoin-ultra','LiteCoin Ultra','');
INSERT INTO BlockchainEntity VALUES('waykichain-governance-coin','WaykiChain Governance Coin','');
INSERT INTO BlockchainEntity VALUES('mouse','MouseMN','');
INSERT INTO BlockchainEntity VALUES('nimiq-2','Nimiq','');
INSERT INTO BlockchainEntity VALUES('nodetrade','Nodetrade','');
INSERT INTO BlockchainEntity VALUES('platon-network','PlatON Network','');
INSERT INTO BlockchainEntity VALUES('peony-coin','Peony Coin','');
INSERT INTO BlockchainEntity VALUES('fixed-trade-coin','Fixed Trade Coin','');
INSERT INTO BlockchainEntity VALUES('dextro','Dextro','');
INSERT INTO BlockchainEntity VALUES('waykichain','WaykiChain','');
INSERT INTO BlockchainEntity VALUES('zencash','Horizen','');
INSERT INTO BlockchainEntity VALUES('maxcoin','Maxcoin','');
INSERT INTO BlockchainEntity VALUES('agenor','Agenor','');
INSERT INTO BlockchainEntity VALUES('songbird','Songbird','');
INSERT INTO BlockchainEntity VALUES('wownero','Wownero','');
INSERT INTO BlockchainEntity VALUES('certik','CertiK','');
INSERT INTO BlockchainEntity VALUES('klimatas','Klimatas','');
INSERT INTO BlockchainEntity VALUES('ycash','Ycash','');
INSERT INTO BlockchainEntity VALUES('primecoin','Primecoin','');
INSERT INTO BlockchainEntity VALUES('hotnow','HotNow','');
INSERT INTO BlockchainEntity VALUES('zaif-token','Zaif Token','');
INSERT INTO BlockchainEntity VALUES('electronero-pulse','Electronero Pulse','');
INSERT INTO BlockchainEntity VALUES('bitcoin-latinum','Bitcoin Latinum','');
INSERT INTO BlockchainEntity VALUES('digitalprice','DigitalPrice','');
INSERT INTO BlockchainEntity VALUES('rupee','Rupee','');
INSERT INTO BlockchainEntity VALUES('historia','Historia','');
INSERT INTO BlockchainEntity VALUES('eosforce','EOSForce','');
INSERT INTO BlockchainEntity VALUES('wild-beast-block','Wild Beast Block','');
INSERT INTO BlockchainEntity VALUES('amazonacoin','AmazonasCoin','');
INSERT INTO BlockchainEntity VALUES('zcoin','Firo','');
INSERT INTO BlockchainEntity VALUES('audax','Audax','');
INSERT INTO BlockchainEntity VALUES('french-digital-reserve','French Digital Reserve','');
INSERT INTO BlockchainEntity VALUES('earnzcoin','EarnzCoin','');
INSERT INTO BlockchainEntity VALUES('soga-project','SOGA Project','');
INSERT INTO BlockchainEntity VALUES('calamari-network','Calamari Network','');
INSERT INTO BlockchainEntity VALUES('help-the-homeless-coin','Help The Homeless Coin','');
INSERT INTO BlockchainEntity VALUES('improved-bitcoin','Improved Bitcoin','');
INSERT INTO BlockchainEntity VALUES('ohm-coin','Ohmcoin','');
INSERT INTO BlockchainEntity VALUES('vantaur','Vantaur','');
INSERT INTO BlockchainEntity VALUES('theta-token','Theta Network','');
INSERT INTO BlockchainEntity VALUES('pokerain','Pokerain','');
INSERT INTO BlockchainEntity VALUES('catscoin','Catscoin','');
INSERT INTO BlockchainEntity VALUES('ionomy','Ionomy','');
INSERT INTO BlockchainEntity VALUES('mineum','Mineum','');
INSERT INTO BlockchainEntity VALUES('bitcoin-vault','Bitcoin Vault','');
INSERT INTO BlockchainEntity VALUES('reecoin','ReeCoin','');
INSERT INTO BlockchainEntity VALUES('fds','Fair Dollars','');
INSERT INTO BlockchainEntity VALUES('geocoin','Geocoin','');
INSERT INTO BlockchainEntity VALUES('bunnycoin','Bunnycoin','');
INSERT INTO BlockchainEntity VALUES('parallelcoin','ParallelCoin','');
INSERT INTO BlockchainEntity VALUES('orbyt-token','ORBYT Token','');
INSERT INTO BlockchainEntity VALUES('turtlecoin','TurtleCoin','');
INSERT INTO BlockchainEntity VALUES('swing','Swing','');
INSERT INTO BlockchainEntity VALUES('maxonrow','Maxonrow','');
INSERT INTO BlockchainEntity VALUES('eros','Eros','');
INSERT INTO BlockchainEntity VALUES('kala','Kala','');
INSERT INTO BlockchainEntity VALUES('gstcoin','GSTCOIN','');
INSERT INTO BlockchainEntity VALUES('pocket-network','Pocket Network','');
INSERT INTO BlockchainEntity VALUES('slimcoin','Slimcoin','');
INSERT INTO BlockchainEntity VALUES('sicash','SICash','');
INSERT INTO BlockchainEntity VALUES('graft-blockchain','Graft Blockchain','');
INSERT INTO BlockchainEntity VALUES('leasehold','Leasehold','');
INSERT INTO BlockchainEntity VALUES('project-pai','Project Pai','');
INSERT INTO BlockchainEntity VALUES('qredit','Qredit','');
INSERT INTO BlockchainEntity VALUES('gastrocoin','GastroCoin','');
INSERT INTO BlockchainEntity VALUES('cryptoflow','Cryptoflow','');
INSERT INTO BlockchainEntity VALUES('defibox','DefiBox','');
INSERT INTO BlockchainEntity VALUES('hondaiscoin','HondaisCoin','');
INSERT INTO BlockchainEntity VALUES('bitwin24','Bitwin24','');
INSERT INTO BlockchainEntity VALUES('internet-computer','Internet Computer','');
INSERT INTO BlockchainEntity VALUES('hupayx','HUPAYX','');
INSERT INTO BlockchainEntity VALUES('nexus','Nexus','');
INSERT INTO BlockchainEntity VALUES('lightforge','Lightforge','');
INSERT INTO BlockchainEntity VALUES('florin','Florin','');
INSERT INTO BlockchainEntity VALUES('citadel','Citadel','');
INSERT INTO BlockchainEntity VALUES('keyco','Keyco','');
INSERT INTO BlockchainEntity VALUES('quotient','Quotient','');
INSERT INTO BlockchainEntity VALUES('beam','BEAM','');
INSERT INTO BlockchainEntity VALUES('pandacoin','Pandacoin','');
INSERT INTO BlockchainEntity VALUES('skycoin','Skycoin','');
INSERT INTO BlockchainEntity VALUES('cowry','COWRY','');
INSERT INTO BlockchainEntity VALUES('safe-coin','Safe','');
INSERT INTO BlockchainEntity VALUES('altcommunity-coin','ALTOM','');
INSERT INTO BlockchainEntity VALUES('bitgert','bitgert','');
INSERT INTO BlockchainEntity VALUES('influxcoin','Influxcoin','');
INSERT INTO BlockchainEntity VALUES('bixb-coin','BixB Coin','');
INSERT INTO BlockchainEntity VALUES('bitclout','Decentralized Social','');
INSERT INTO BlockchainEntity VALUES('myriadcoin','Myriad','');
INSERT INTO BlockchainEntity VALUES('lanacoin','LanaCoin','');
INSERT INTO BlockchainEntity VALUES('hicoin','HiCoin','');
INSERT INTO BlockchainEntity VALUES('visio','Visio','');
INSERT INTO BlockchainEntity VALUES('classzz','ClassZZ','');
INSERT INTO BlockchainEntity VALUES('gigecoin','GigEcoin','');
INSERT INTO BlockchainEntity VALUES('actinium','Actinium','');
INSERT INTO BlockchainEntity VALUES('purple-butterfly-trading','Purple Butterfly Trading','');
INSERT INTO BlockchainEntity VALUES('eska','Eska','');
INSERT INTO BlockchainEntity VALUES('newton-project','Newton Project','');
INSERT INTO BlockchainEntity VALUES('sienna','Sienna','');
INSERT INTO BlockchainEntity VALUES('leafcoin','Leafcoin','');
INSERT INTO BlockchainEntity VALUES('nasdacoin','Nasdacoin','');
INSERT INTO BlockchainEntity VALUES('vpncoin','VPNCoin','');
INSERT INTO BlockchainEntity VALUES('chimaera','XAYA','');
INSERT INTO BlockchainEntity VALUES('bitcoinstaking','BitcoinStaking','');
INSERT INTO BlockchainEntity VALUES('piratecash','PirateCash','');
INSERT INTO BlockchainEntity VALUES('whive','Whive','');
INSERT INTO BlockchainEntity VALUES('edc-blockchain','EDC Blockchain','');
INSERT INTO BlockchainEntity VALUES('ecodollar','EcoDollar','');
INSERT INTO BlockchainEntity VALUES('binjit-coin','Binjit Coin','');
INSERT INTO BlockchainEntity VALUES('dcoin-token','Dcoin Token','');
INSERT INTO BlockchainEntity VALUES('sharkcoin','Sharkcoin','');
INSERT INTO BlockchainEntity VALUES('bitcoinv','BitcoinV','');
INSERT INTO BlockchainEntity VALUES('anon','ANON','');
INSERT INTO BlockchainEntity VALUES('bitcoin-hd','Bitcoin HD','');
INSERT INTO BlockchainEntity VALUES('amoveo','Amoveo','');
INSERT INTO BlockchainEntity VALUES('bitcoin','Bitcoin','https://mempool.space/');
INSERT INTO BlockchainEntity VALUES('bitcoin-testnet4','Bitcoin','https://mempool.space/testnet4/');
INSERT INTO BlockchainEntity VALUES('kemacoin','KemaCoin','');
INSERT INTO BlockchainEntity VALUES('nav-coin','Navcoin','');
INSERT INTO BlockchainEntity VALUES('otocash','OTOCASH','');
INSERT INTO BlockchainEntity VALUES('placeh','Placeholders','');
INSERT INTO BlockchainEntity VALUES('pepegold','PEPS Coin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-atom','Bitcoin Atom','');
INSERT INTO BlockchainEntity VALUES('xeonbit','Xeonbit','');
INSERT INTO BlockchainEntity VALUES('ethup','ETHUP','');
INSERT INTO BlockchainEntity VALUES('infchain','InfChain','');
INSERT INTO BlockchainEntity VALUES('coinbase-stock','Coinbase Tokenized Stock on FTX','');
INSERT INTO BlockchainEntity VALUES('kujira','Kujira','');
INSERT INTO BlockchainEntity VALUES('groestlcoin','Groestlcoin','');
INSERT INTO BlockchainEntity VALUES('bitvote','Bitvote','');
INSERT INTO BlockchainEntity VALUES('supercoin','SuperCoin','');
INSERT INTO BlockchainEntity VALUES('ergo','Ergo','');
INSERT INTO BlockchainEntity VALUES('persistence','Persistence','');
INSERT INTO BlockchainEntity VALUES('cryptosaga','CryptoSaga','');
INSERT INTO BlockchainEntity VALUES('rei-network','REI Network','');
INSERT INTO BlockchainEntity VALUES('ball-coin','BALL Coin','');
INSERT INTO BlockchainEntity VALUES('bytz','BYTZ','');
INSERT INTO BlockchainEntity VALUES('netbox-coin','Netbox Coin','');
INSERT INTO BlockchainEntity VALUES('martexcoin','MarteXcoin','');
INSERT INTO BlockchainEntity VALUES('vectorium','Vectorium','');
INSERT INTO BlockchainEntity VALUES('encocoinplus','Encocoinplus','');
INSERT INTO BlockchainEntity VALUES('electroneum','Electroneum','');
INSERT INTO BlockchainEntity VALUES('zarcash','Zarhexcash','');
INSERT INTO BlockchainEntity VALUES('graviocoin','Graviocoin','');
INSERT INTO BlockchainEntity VALUES('theta-fuel','Theta Fuel','');
INSERT INTO BlockchainEntity VALUES('digibyte','DigiByte','');
INSERT INTO BlockchainEntity VALUES('iq-cash','IQ.cash','');
INSERT INTO BlockchainEntity VALUES('stronghands-masternode','StrongHands Masternode','');
INSERT INTO BlockchainEntity VALUES('audiocoin','AudioCoin','');
INSERT INTO BlockchainEntity VALUES('newyorkcoin','NewYorkCoin','');
INSERT INTO BlockchainEntity VALUES('zano','Zano','');
INSERT INTO BlockchainEntity VALUES('electronicgulden','Electronic Gulden','');
INSERT INTO BlockchainEntity VALUES('crevacoin','Crevacoin','');
INSERT INTO BlockchainEntity VALUES('icolcoin','Icolcoin','');
INSERT INTO BlockchainEntity VALUES('coinbase-stock-bittrex','Coinbase Tokenized Stock on Bittrex','');
INSERT INTO BlockchainEntity VALUES('euno','EUNO','');
INSERT INTO BlockchainEntity VALUES('safe-deal','SafeDeal','');
INSERT INTO BlockchainEntity VALUES('zetacoin','Zetacoin','');
INSERT INTO BlockchainEntity VALUES('particl','Particl','');
INSERT INTO BlockchainEntity VALUES('cube','cube','');
INSERT INTO BlockchainEntity VALUES('chesscoin-0-32','ChessCoin 0.32%','');
INSERT INTO BlockchainEntity VALUES('denarius','Denarius','');
INSERT INTO BlockchainEntity VALUES('greencoin','Greencoin','');
INSERT INTO BlockchainEntity VALUES('bitzeny','BitZeny','');
INSERT INTO BlockchainEntity VALUES('mobit-global','Mobit Global','');
INSERT INTO BlockchainEntity VALUES('mapcoin','MapCoin','');
INSERT INTO BlockchainEntity VALUES('elementrem','Elementrem','');
INSERT INTO BlockchainEntity VALUES('bbscoin','BBSCoin','');
INSERT INTO BlockchainEntity VALUES('verus-coin','Verus Coin','');
INSERT INTO BlockchainEntity VALUES('scholarship-coin','Scholarship Coin','');
INSERT INTO BlockchainEntity VALUES('safe-seafood-coin','Safe SeaFood Coin','');
INSERT INTO BlockchainEntity VALUES('hush','Hush','');
INSERT INTO BlockchainEntity VALUES('vault','VAULT','');
INSERT INTO BlockchainEntity VALUES('etherzero','Ether Zero','');
INSERT INTO BlockchainEntity VALUES('songcoin','SongCoin','');
INSERT INTO BlockchainEntity VALUES('advanced-internet-block','Advanced Integrated Blocks','');
INSERT INTO BlockchainEntity VALUES('yacoin','YACoin','');
INSERT INTO BlockchainEntity VALUES('caluracoin','CaluraCoin','');
INSERT INTO BlockchainEntity VALUES('innova','Innova','');
INSERT INTO BlockchainEntity VALUES('blockstamp','BlockStamp','');
INSERT INTO BlockchainEntity VALUES('centurion','Centurion','');
INSERT INTO BlockchainEntity VALUES('foxdcoin','Foxdcoin','');
INSERT INTO BlockchainEntity VALUES('spectrecoin','Alias','');
INSERT INTO BlockchainEntity VALUES('king-money','King Money','');
INSERT INTO BlockchainEntity VALUES('epic-cash','Epic Cash','');
INSERT INTO BlockchainEntity VALUES('feathercoin','Feathercoin','');
INSERT INTO BlockchainEntity VALUES('atlas-protocol','Atlas Protocol','');
INSERT INTO BlockchainEntity VALUES('agouti','Agouti','');
INSERT INTO BlockchainEntity VALUES('octocoin','Octocoin','');
INSERT INTO BlockchainEntity VALUES('veles','Veles','');
INSERT INTO BlockchainEntity VALUES('cryptokenz','Cryptokenz','');
INSERT INTO BlockchainEntity VALUES('cypherium','Cypherium','');
INSERT INTO BlockchainEntity VALUES('hitcoin','Hitcoin','');
INSERT INTO BlockchainEntity VALUES('bittokens','BitTokens','');
INSERT INTO BlockchainEntity VALUES('tictalk','TicTalk','');
INSERT INTO BlockchainEntity VALUES('strayacoin','Strayacoin','');
INSERT INTO BlockchainEntity VALUES('ecobit','Ecobit','');
INSERT INTO BlockchainEntity VALUES('litecoin-plus','Litecoin Plus','');
INSERT INTO BlockchainEntity VALUES('peepcoin','Peepcoin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-final','Bitcoin Final','');
INSERT INTO BlockchainEntity VALUES('delion','Delion','');
INSERT INTO BlockchainEntity VALUES('sapphire','Sapphire','');
INSERT INTO BlockchainEntity VALUES('insights-network','INSTAR','');
INSERT INTO BlockchainEntity VALUES('bitcanna','BitCanna','');
INSERT INTO BlockchainEntity VALUES('halo-platform','Halo Platform','');
INSERT INTO BlockchainEntity VALUES('pluracoin','PluraCoin','');
INSERT INTO BlockchainEntity VALUES('tokyo','Tokyo Coin','');
INSERT INTO BlockchainEntity VALUES('ryo','Ryo Currency','');
INSERT INTO BlockchainEntity VALUES('vollar','V-Dimension','');
INSERT INTO BlockchainEntity VALUES('swiftcash','SwiftCash','');
INSERT INTO BlockchainEntity VALUES('riecoin','Riecoin','');
INSERT INTO BlockchainEntity VALUES('devault','DeVault','');
INSERT INTO BlockchainEntity VALUES('thebigcoin','TheBigCoin','');
INSERT INTO BlockchainEntity VALUES('swamp-coin','Swamp Coin','');
INSERT INTO BlockchainEntity VALUES('nusd-hotbit','nUSD (HotBit)','');
INSERT INTO BlockchainEntity VALUES('inflationcoin','InflationCoin','');
INSERT INTO BlockchainEntity VALUES('yadacoin','YadaCoin','');
INSERT INTO BlockchainEntity VALUES('bitz','bitz','');
INSERT INTO BlockchainEntity VALUES('electronero','Electronero','');
INSERT INTO BlockchainEntity VALUES('simplexchain','SimplexChain','');
INSERT INTO BlockchainEntity VALUES('memetic','Memetic','');
INSERT INTO BlockchainEntity VALUES('coin4trade','Coin4Trade','');
INSERT INTO BlockchainEntity VALUES('hidden-coin','Hidden Coin','');
INSERT INTO BlockchainEntity VALUES('chaincoin','Chaincoin','');
INSERT INTO BlockchainEntity VALUES('hyper-pay','Hyper Pay','');
INSERT INTO BlockchainEntity VALUES('curvehash','CURVEHASH','');
INSERT INTO BlockchainEntity VALUES('evrice','Evrice','');
INSERT INTO BlockchainEntity VALUES('i0coin','I0Coin','');
INSERT INTO BlockchainEntity VALUES('monero-classic-xmc','Monero-Classic','');
INSERT INTO BlockchainEntity VALUES('kzcash','Kzcash','');
INSERT INTO BlockchainEntity VALUES('triton','Equilibria','');
INSERT INTO BlockchainEntity VALUES('terra-luna','Terra','');
INSERT INTO BlockchainEntity VALUES('croat','CROAT','');
INSERT INTO BlockchainEntity VALUES('oec-token','OEC Token','');
INSERT INTO BlockchainEntity VALUES('sovereign-coin','Sovereign Coin','');
INSERT INTO BlockchainEntity VALUES('omni','Omni','');
INSERT INTO BlockchainEntity VALUES('neo','NEO','');
INSERT INTO BlockchainEntity VALUES('klay-token','Klaytn','');
INSERT INTO BlockchainEntity VALUES('zilliqa','Zilliqa','');
INSERT INTO BlockchainEntity VALUES('elastos','elastos','');
INSERT INTO BlockchainEntity VALUES('moonriver','Moonriver','https://blockscout.moonriver.moonbeam.network/address/$ref');
INSERT INTO BlockchainEntity VALUES('ardor','Ardor','');
INSERT INTO BlockchainEntity VALUES('binancecoin','BNB Beacon Chain','https://explorer.binance.org/');
INSERT INTO BlockchainEntity VALUES('stellar','Stellar','');
INSERT INTO BlockchainEntity VALUES('optimistic-ethereum','Optimism','https://optimistic.etherscan.io/token/$ref');
INSERT INTO BlockchainEntity VALUES('ledgis','Ledgis','');
INSERT INTO BlockchainEntity VALUES('mojocoin','Mojocoin','');
INSERT INTO BlockchainEntity VALUES('earthcoin','Earthcoin','');
INSERT INTO BlockchainEntity VALUES('wax','WAX','');
INSERT INTO BlockchainEntity VALUES('maza','Maza','');
INSERT INTO BlockchainEntity VALUES('pirate-chain','Pirate Chain','');
INSERT INTO BlockchainEntity VALUES('bitcoin-diamond','Bitcoin Diamond','');
INSERT INTO BlockchainEntity VALUES('1337','Elite','');
INSERT INTO BlockchainEntity VALUES('starcoin','Starcoin','');
INSERT INTO BlockchainEntity VALUES('mantis-network','Mantis Network','');
INSERT INTO BlockchainEntity VALUES('webdollar','webdollar','');
INSERT INTO BlockchainEntity VALUES('infinite-ricks','Infinite Ricks','');
INSERT INTO BlockchainEntity VALUES('fandom-chain','Fandom Chain','');
INSERT INTO BlockchainEntity VALUES('swap','Swap','');
INSERT INTO BlockchainEntity VALUES('betller-coin','Betller Coin','');
INSERT INTO BlockchainEntity VALUES('noblecoin','NobleCoin','');
INSERT INTO BlockchainEntity VALUES('2acoin','2ACoin','');
INSERT INTO BlockchainEntity VALUES('bitcoinmono','BitcoinMono','');
INSERT INTO BlockchainEntity VALUES('newton-coin-project','Newton Coin Project','');
INSERT INTO BlockchainEntity VALUES('grimm','Grimm','');
INSERT INTO BlockchainEntity VALUES('litebitcoin','LiteBitcoin','');
INSERT INTO BlockchainEntity VALUES('cryptonex','Cryptonex','');
INSERT INTO BlockchainEntity VALUES('veggiecoin','VeggieCoin','');
INSERT INTO BlockchainEntity VALUES('plex','PLEX','');
INSERT INTO BlockchainEntity VALUES('ulord','Ulord','');
INSERT INTO BlockchainEntity VALUES('bitcoin-stash','Bitcoin Stash','');
INSERT INTO BlockchainEntity VALUES('gridcoin-research','Gridcoin','');
INSERT INTO BlockchainEntity VALUES('artax','ARTAX','');
INSERT INTO BlockchainEntity VALUES('smartcash','SmartCash','');
INSERT INTO BlockchainEntity VALUES('goldcoin','Goldcoin','');
INSERT INTO BlockchainEntity VALUES('nextexchange','NEXT','');
INSERT INTO BlockchainEntity VALUES('navibration','Navibration','');
INSERT INTO BlockchainEntity VALUES('investdigital','InvestDigital','');
INSERT INTO BlockchainEntity VALUES('xdai','xDAI','https://blockscout.com/xdai/mainnet/address/$ref');
INSERT INTO BlockchainEntity VALUES('arbitrum-one','Arbitrum','https://arbiscan.io/token/$ref');
INSERT INTO BlockchainEntity VALUES('okex-chain','OKExChain','https://www.oklink.com/oec/address/$ref');
INSERT INTO BlockchainEntity VALUES('fuse','Fuse','');
INSERT INTO BlockchainEntity VALUES('cosmos','Cosmos','');
INSERT INTO BlockchainEntity VALUES('link','LINK','');
INSERT INTO BlockchainEntity VALUES('dune','Dune','');
INSERT INTO BlockchainEntity VALUES('oduwa-coin','Oduwa Coin','');
INSERT INTO BlockchainEntity VALUES('orient-walt','Orient Walt','');
INSERT INTO BlockchainEntity VALUES('mbitbooks','MBitBooks','');
INSERT INTO BlockchainEntity VALUES('gard-governance-token','GARD Governance Token','');
INSERT INTO BlockchainEntity VALUES('azus','Azus','');
INSERT INTO BlockchainEntity VALUES('city-coin','City Coin','');
INSERT INTO BlockchainEntity VALUES('gobyte','GoByte','');
INSERT INTO BlockchainEntity VALUES('01coin','01coin','');
INSERT INTO BlockchainEntity VALUES('casper-network','Casper Network','');
INSERT INTO BlockchainEntity VALUES('bithostcoin','BitHostCoin','');
INSERT INTO BlockchainEntity VALUES('bitcoinbam','BitcoinBam','');
INSERT INTO BlockchainEntity VALUES('lobstex-coin','Lobstex','');
INSERT INTO BlockchainEntity VALUES('yenten','YENTEN','');
INSERT INTO BlockchainEntity VALUES('counos-coin','Counos Coin','');
INSERT INTO BlockchainEntity VALUES('lbry-credits','LBRY Credits','');
INSERT INTO BlockchainEntity VALUES('lyra','Lyra','');
INSERT INTO BlockchainEntity VALUES('gapcoin','Gapcoin','');
INSERT INTO BlockchainEntity VALUES('neetcoin','Neetcoin','');
INSERT INTO BlockchainEntity VALUES('helpico','Helpico','');
INSERT INTO BlockchainEntity VALUES('prime-xi','Prime-XI','');
INSERT INTO BlockchainEntity VALUES('sorachancoin','SorachanCoin','');
INSERT INTO BlockchainEntity VALUES('bitcoin-trust','Bitcoin Trust','');
INSERT INTO BlockchainEntity VALUES('blockidcoin','Blockidcoin','');
INSERT INTO BlockchainEntity VALUES('bean-cash','Bean Cash','');
INSERT INTO BlockchainEntity VALUES('twist','TWIST','');
INSERT INTO BlockchainEntity VALUES('taler','Taler','');
INSERT INTO BlockchainEntity VALUES('casinocoin','Casinocoin','');
INSERT INTO BlockchainEntity VALUES('mixin','Mixin','');
INSERT INTO BlockchainEntity VALUES('radix','Radix','');
INSERT INTO BlockchainEntity VALUES('dimecoin','Dimecoin','');
INSERT INTO BlockchainEntity VALUES('terracoin','Terracoin','');
INSERT INTO BlockchainEntity VALUES('knoxfs','KnoxFS','');
INSERT INTO BlockchainEntity VALUES('rapids','Rapids','');
INSERT INTO BlockchainEntity VALUES('hacash','Hacash','');
INSERT INTO BlockchainEntity VALUES('infinitecoin','Infinitecoin','');
INSERT INTO BlockchainEntity VALUES('quebecoin','Quebecoin','');
INSERT INTO BlockchainEntity VALUES('wonderfi-tokenized-stock','WonderFi Tokenized Stock','');
INSERT INTO BlockchainEntity VALUES('bitbar','Bitbar','');
INSERT INTO BlockchainEntity VALUES('electra','Electra','');
INSERT INTO BlockchainEntity VALUES('syscoin','Syscoin NEVM','');
INSERT INTO BlockchainEntity VALUES('near-protocol','Near Protocol','');
INSERT INTO BlockchainEntity VALUES('ronin','Ronin','');
INSERT INTO BlockchainEntity VALUES('avalanche','Avalanche','https://snowtrace.io/tx/$ref');
INSERT INTO BlockchainEntity VALUES('rootstock','Rootstock RSK','');
INSERT INTO BlockchainEntity VALUES('telos','Telos','');
INSERT INTO BlockchainEntity VALUES('theta','Theta','');
INSERT INTO BlockchainEntity VALUES('aurora','Aurora','');
INSERT INTO BlockchainEntity VALUES('solana','Solana','https://explorer.solana.com/address/$ref');
INSERT INTO BlockchainEntity VALUES('moonbeam','Moonbeam','');
INSERT INTO BlockchainEntity VALUES('boba','Boba Network','');
INSERT INTO BlockchainEntity VALUES('cardano','Cardano','');
INSERT INTO BlockchainEntity VALUES('Bitcichain','Bitcichain','');
INSERT INTO BlockchainEntity VALUES('xdc-network','xdc-network','');
INSERT INTO BlockchainEntity VALUES('cronos','Cronos','');
INSERT INTO BlockchainEntity VALUES('vechain','VeChain','');
INSERT INTO BlockchainEntity VALUES('kava','Kava','');
INSERT INTO BlockchainEntity VALUES('gnosis','Gnosis','https://gnosisscan.io/address/$ref');
INSERT INTO BlockchainEntity VALUES('ethereum-classic','Ethereum Classic','');
INSERT INTO BlockchainEntity VALUES('osmosis','Osmosis','');
INSERT INTO BlockchainEntity VALUES('algorand','Algorand','');
INSERT INTO BlockchainEntity VALUES('waves','Waves','');
INSERT INTO BlockchainEntity VALUES('celo','Celo','');
INSERT INTO BlockchainEntity VALUES('chiliz','Chiliz','');
INSERT INTO BlockchainEntity VALUES('factom','Factom','');
INSERT INTO BlockchainEntity VALUES('tron','TRON','');
INSERT INTO BlockchainEntity VALUES('iotex','IoTeX','https://iotexscan.io/token/$ref');
INSERT INTO BlockchainEntity VALUES('fantom','Fantom','https://ftmscan.com/token/$ref');
INSERT INTO BlockchainEntity VALUES('astar','astar','');
INSERT INTO BlockchainEntity VALUES('ethereum','Ethereum','https://etherscan.io/');
INSERT INTO BlockchainEntity VALUES('ethereum-goerli','Ethereum Goerli','https://goerli.etherscan.io/');
INSERT INTO BlockchainEntity VALUES('ethereum-sepolia','Ethereum Sepolia','https://sepolia.etherscan.io/');
INSERT INTO BlockchainEntity VALUES('qtum','Qtum','');
INSERT INTO BlockchainEntity VALUES('metis-andromeda','Metis Andromeda','');
INSERT INTO BlockchainEntity VALUES('binance-smart-chain','Binance Smart Chain','https://bscscan.com/');
INSERT INTO BlockchainEntity VALUES('bsc-testnet','Binance Smart Chain Testnet','https://testnet.bscscan.com/');
INSERT INTO BlockchainEntity VALUES('meter','Meter','');
INSERT INTO BlockchainEntity VALUES('smartbch','SmartBCH','');
INSERT INTO BlockchainEntity VALUES('evmos','Evmos','');
INSERT INTO BlockchainEntity VALUES('xrp','XRP Ledger','');
INSERT INTO BlockchainEntity VALUES('ontology','Ontology','');
INSERT INTO BlockchainEntity VALUES('kucoin-community-chain','Kucoin Community Chain','');
INSERT INTO BlockchainEntity VALUES('secret','Secret','');
INSERT INTO BlockchainEntity VALUES('eos','EOS','https://eosauthority.com/');
INSERT INTO BlockchainEntity VALUES('eos-jungle-testnet','EOS','https://jungle4.cryptolions.io/v2/explore/');
INSERT INTO BlockchainEntity VALUES('eos-evm','EOS','https://explorer.evm.eosnetwork.com/');
INSERT INTO BlockchainEntity VALUES('polygon-pos','Polygon','https://polygonscan.com/');
INSERT INTO BlockchainEntity VALUES('polygon-mumbai','Polygon Mumbai','https://mumbai.polygonscan.com/');
INSERT INTO BlockchainEntity VALUES('fusion-network','Fusion Network','');
INSERT INTO BlockchainEntity VALUES('wanchain','Wanchain','');
INSERT INTO BlockchainEntity VALUES('elrond','Elrond','');
INSERT INTO BlockchainEntity VALUES('openledger','OpenLedger','');
INSERT INTO BlockchainEntity VALUES('ethereum-holesky','Ethereum Holesky','https://holesky.etherscan.io/');
COMMIT;